export const officialBoardCategoriesMock = [
  {
    IdKategorie: 'Bytová náhrada - zákon č. 260 z r. 2011',
    Nazev: 'Bytová náhrada',
    PocetVyveseno: '0',
    PocetArchiv: '0',
  },
  {
    IdKategorie: 'Iné úradné oznamy',
    Nazev: 'Iné úradné oznamy',
    PocetVyveseno: '5',
    PocetArchiv: '275',
  },
  {
    IdKategorie: 'Komunálne voľby',
    Nazev: 'Komunálne voľby',
    PocetVyveseno: '1',
    PocetArchiv: '41',
  },
  {
    IdKategorie: 'Mestská rada a zastupiteľstvo',
    Nazev: 'Mestská rada a zastupiteľstvo',
    PocetVyveseno: '0',
    PocetArchiv: '169',
  },
  {
    IdKategorie: 'Návrhy VzN a dodatkov k Štatútu na pripomienkovani',
    Nazev: 'Návrhy VzN, dodatkov k Štatútu na pripomienkovanie',
    PocetVyveseno: '0',
    PocetArchiv: '58',
  },
  {
    IdKategorie: 'Oznámenia o dražbe',
    Nazev: 'Dražba',
    PocetVyveseno: '8',
    PocetArchiv: '479',
  },
  {
    IdKategorie: 'Posudzovanie vplyvov na životné prostredie',
    Nazev: 'Posudzovanie vplyvov na životné prostredie',
    PocetVyveseno: '8',
    PocetArchiv: '875',
  },
  {
    IdKategorie: 'Rozpočet hl.m. SR Bratislavy',
    Nazev: 'Rozpočet',
    PocetVyveseno: '0',
    PocetArchiv: '12',
  },
  {
    IdKategorie: 'Smogový varovný signál',
    Nazev: 'Smogový varovný signál',
    PocetVyveseno: '0',
    PocetArchiv: '6',
  },
  {
    IdKategorie: 'Sociálne služby',
    Nazev: 'Sociálne služby',
    PocetVyveseno: '3',
    PocetArchiv: '10',
  },
  {
    IdKategorie: 'Stavebné povolenia',
    Nazev: 'Stavebné povolenia',
    PocetVyveseno: '0',
    PocetArchiv: '202',
  },
  {
    IdKategorie: 'Udržba komunikácií',
    Nazev: 'Údržba komunikácií',
    PocetVyveseno: '122',
    PocetArchiv: '2410',
  },
  {
    IdKategorie: 'Verejné obstarávanie',
    Nazev: 'Verejné obstarávanie',
    PocetVyveseno: '26',
    PocetArchiv: '39',
  },
  {
    IdKategorie: 'Verejné vyhlášky',
    Nazev: 'Verejné vyhlášky',
    PocetVyveseno: '8',
    PocetArchiv: '1621',
  },
  {
    IdKategorie: 'Verejný návrh',
    Nazev: 'Verejný návrh',
    PocetVyveseno: '0',
    PocetArchiv: '3',
  },
  {
    IdKategorie: 'Všeobecne záväzné nariadenia',
    Nazev: 'Všeobecne záväzné nariadenia a Štatút hl.m.',
    PocetVyveseno: '1',
    PocetArchiv: '139',
  },
  {
    IdKategorie: 'Výberové konania a zamestnanie',
    Nazev: 'Výberové konania a zamestnanie',
    PocetVyveseno: '15',
    PocetArchiv: '1552',
  },
  {
    IdKategorie: 'Výsledky vybavenia petícií',
    Nazev: 'Petície a sťažnosti',
    PocetVyveseno: '17',
    PocetArchiv: '82',
  },
  {
    IdKategorie: 'Zámery, verejné súťaže a dražby',
    Nazev: 'Zámery, verejné súťaže a dražby',
    PocetVyveseno: '0',
    PocetArchiv: '373',
  },
  {
    IdKategorie: 'Životné prostredie, mestská zeleň',
    Nazev: 'Životné prostredie, mestská zeleň',
    PocetVyveseno: '1',
    PocetArchiv: '255',
  },
  {
    IdKategorie: 'Územné plánovanie, Územný rozvoj mesta',
    Nazev: 'Územné plánovanie a rozvoj',
    PocetVyveseno: '0',
    PocetArchiv: '42',
  },
]
