---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    CONTENT_INVENTORY_API_KEY: AgAkmArCxAwP8UshbrKKqdLht4qJd/ia+7fS57fHYDKoQL+FtV1MXIFKrSWEcIF4G2QpsUd3xj+vWcJENk5WdFJiUo4MNhBI9o6dqlgBCSZ4JRU8KsLmgdLemsz9Np/BSHlkEgJZ2ihiBcH4TBwKeVv0kEmjV5v90qkb3L218ltVar7McotV6OHLLzSGXwb3VKqFZ1EMA2CueisWqhWMS1IsVLOnuyzHNBIa0VytKwuNyW+/eS9kDR3/5PAyp7MJ/KZgwjaqvgJ6Eb4FzQ1zp5DLUCphm0LTGcV0vNTigYW2JORaeKPCNaFLBs0XjVuGGPq80H5wGNGicOmgyy6x6C7M4mpTxGHsenhJOKzE73oGOL5QFv1+Qx2YPHCqv3U4UrN4WzhvsOxL6Y/SaqkxMrcOlOqyEXOh3yaYIhaGE59Xh/kOz409iml8RsZK4wVYVLf9oA/HNgV8kBoNLgXkOYGr5ZvQ4OM5vzF6eI3hXJ+6X77pVB5K6buhwSYDjTck1jahsoUI0xvn4Icbc4h4m2mhtnrCCaxn42Pouy+DSoLF3Et9HvJvidEZXN93Lf5gFQhSysgWMQhw7lXGXBknMKAxW9yE+OfxgHShrllYD2OqjgB53a882YgePb5oiziaok1UFdA0el+dJldpl+nYn5EjiXJqt5AMterk6M/cAtxT362KqlKhlcQbgwgzVYiIP708L7tVqyszE2wGx2C7Z4Usk+MJK5h3v+pV4joSxXMcdA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
      namespace: ${NAMESPACE}
