---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-msal-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgB9JRK/46iF3G1B3Va5WQHwSxSbWEBjYNk2MShJpT/h1BgEAU1194Sd/0pBtINeKIjJyVDDrun5yvLng6KOfCiFw/Dk5SjGED4mIjqaoytWPZ7cOc3qFnZxp1wx3arpCXWmCvnBjyHYjkVd8IaLq1f2i4vx+M3wrVyuASUKUtGMzPw8PpTcDIOLa6W0s+gxwOxbZ0A5f3WPloUblO8vvLojosKr5G3J2vXGml73PHm7eUQgIpxp4Dp+Pwsvo3KYCRte/ZaP9y3fmyeJXVw0dYZ4uVMnQN5jPffYx7GcpJpcCFCWuRAgHC+GF0TRsMRu/B04jj1rJuXUcD/CCIosGvo9J4ALWipgU1heoNwB0fdw8hAh9WwHq2EDgVjt3mBFkkRuuJ8dE9y/qP0dU/mK99sD41DvEFaQjT1it8s4Xg0eXvDZHnNFUvPdvgQJhLo39kyd1b6fHDsth+KpblpP91Uy6HXQZy6nzr1sO+IyR4c/yDJEbpefgsWESPjoCk5uWjx7g6DRXm3ttpxYxfvSknVxQO0X8jamk+YqeQFuXUytqDvlIo/GLFpwXqQHu/+Um/XNCp6299ixHH/0ffDBAQOHlzMOL1JIw971zxZ/hw96nI88TtAoOd7NlD5VeZJGrn2B7qN2jMx014ApSl5OLi7emKwzt7R6knj+Vhf4/pucr6gMYW9N/583rjO70SDYXj457iMVT/o8w0am56bYkB3Xe11zUSyKXmEcMZLp1NJ9xXt/f61SGddl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-msal-secret
      namespace: ${NAMESPACE}
