apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-msal-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgDCpoumXlJ5kNESR63rmHAjh5kaVF/X2CIBCsfP5oVFbvJLPQyBWIM5sV1tsRE5kWam61+qEB+KBwzwpAYVURqIbvjTLrGBxk8xpZZMBY/ZNYGqX8eW27zwBmtZFeIDu07R+Xj/ntSn6OggZ49f80TfGv9BkKvvkUlGPWBc1lgBEkcN2wNZYVeBUGVEBl9vPar64bo6sActh1OU0QpMNOpb8GKgC5HEo6SqDHc7tKHqux7lW787yDgGlgUqN5claU4MhIFcVys0cTf/2OeK9sb5cvEUHn7reY+AJDy/mZ/HlmJl+taI5WXsZ5M26Zgwybfin0Xw+lkA0x4VOo/W4q18yGMupuTGxcv2Agd8s44u1CTfLUuJ3VxZ+ETwDz764dSyjf76mpxG6qSnkKJXxHS+5s6RMYyYZL84ELgikSwMMMQ99NN/Oyse0lTykp4sVMxrYGh4QOHcD4/zsLYThPelwpCMdyuzPuLGciHwmnTthCFCgjUSdNeTluauwkdLBlw0Km50KKut25hpkgaqx4y4YjSN8IntkTDcLT9kmI5xXJhDs7p2SLZlPaSAlMaMUFfpqoIrknLt2aW0LoxfrK/WuigKCnKZRIkRD0fXdMvUAL7EcmDdC2BZHCqENdX+1sae9w4+YofPnvzEajSvgLy2vc4ber6cT+hg0tknziSFiOWBRIqwPifyBZcqbELpnaaYvjSY3Vr4qTleZ+ERBvIIN63Z7mvZBQXCOCyYH5hBARIsozpDgIK2
  template:
    data: 
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: "${BUILD_REPOSITORY_NAME}"
        source: "${BUILD_REPOSITORY_NAME}"
      name: ${BUILD_REPOSITORY_NAME}-msal-secret
      namespace: "${NAMESPACE}"
