---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    CONTENT_INVENTORY_API_KEY: AgAqvOnQWZ5ykYTZA1Ul/xON5G8sJJ2nS38xXnk6HmtjHAFd/+ao/mH3Afl7GomY+HM4FImaaVYU62dzDvmFRtOHs1QlSSiS/OcqzIda8Tcw1qtlsJyL0xHwKogEGOskKhtP/43kqznbLVYSwQ76WZ3sdxZhBJgnYX+dDgv4A6Ty5oXwb2EQve2kPkWl9471jo4d02onXUWEYxotxZ7Xp8UNybXUC1kHNz4CvhXSfN1ax2z0DdYFB5CzlwK9uiXiilTKKY9iomjfLSsXkXPyxAdA3cgPIu1/1DbN+J4KjYWpR8A2qc6laTC/icw+gFEPtMrhGLeVesIxs9b5Mk3Koa49wslSUoBqz3Vpvy2KgPY4Q0dC56IEQLFoHkdf/nIgsa8kV+i5mHcHmTgmjyvLbBr+E0x7UkXi7QdT9Z6ln4GXlANLUQEYhTZdkrpb3vyHLJVNfark/c4569+R+o5ZLFiy1AXKfcgyPpktRLlbpy6CMdhbLJzpWVwGKhh83qu7fxfsVY/gAhJlpQh5OjffojRNd8UeklsSosUPiac87yqNQ+3dfkuGIAtzslfjsw0GuG1FIvpVvgwXZjlIyMw1B4cg/xA8fJUqz0tE6x1AtOze8vQvOJjFA3wxR7luyk4JO0u4yXElCDNr/tMyqufhJpLLeMjYMPTJLduEZ+iegYGHQdY07C/Ik4cj1fT9Kx1JqlXc67lx5ZSNvvjFOLNR0r15Oz3lXX+2+mYU1tk67xhCcg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
      namespace: ${NAMESPACE}
