---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-msal-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgCAGaUCAYVOFOqtjMksL+80almEba1mtc1T2oYHxmfdy5fkNTOYhua83wk9rgWv3K2daEtqhs7MfWN7CeTY50ZbD4nRrcLpA6avnlZ8YDWAwq3mAGKtDWvFNQQLz3hxft2YYia4rke2xMbVdua5JqjpiMatJwISwZEb8TPNDndltR+INztPY4+K35EnOalhhbRsh1KRoed3qSVjTLNTlNUP+tQt9HdBKzl6pIMdv1mNyGc/SCgU5wU0OUALlDuid0hNjsb46W/fc84si97de88tBScU2GxhHX3BFLBRAyQgzHZmAnMYH18UTCmKEpRl+rbdMMNUgiPrEmBiS9RtAtuMlQZQTG3xR8P2uxC6lm0i1zV6Skum5ESvZu1OugU/SVkGwMGV3VXKoeAQHGMZeQWqXi5oTrUrrFqxO+9JKKWWLcWFXHZaU9ECnwmeQ7c1gi6Txhl3BuyOZY1W2jmQkz9X48CYHhdXqTaUU5civMedQsQKAfz5f2gnOTdKqcZYujzakZOCKQNZVG6zw3Ydpz1B7bQ1wgPEcWzsVIaF3w3AMh/0+2dCBxIaGzMNfOno3eVUJhyQX/Bef45qCTgqisPOlMigdtrr/f2vOBa2wqepromzWJB/+w16jyoZTU1Mvjhp3hpZXKsaIkqAShhYrkoP4u/2fhv0a/V1PKc1dIifGblj90KUFd60vlvV2G/bzIz9el896TNK0XPjNiKMXLUYWU616WTVBagIKEVnUN5UiLqU9cTVCfkD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-msal-secret
      namespace: ${NAMESPACE}
