apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: bratislava-next-revalidate-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_REVALIDATE_SECRET_TOKEN: AgBOCvlqNhN9MR+tfXwQnL+P4Ayp1NhxnUGGkRzrA7R7oO8GNVA+GxQ65suLPrTn5wu5uIMqOSOB/7Mzh+W16JTzgY4xwO/goh4/wzRonKiGNTt07yJpzZ2EluXoxnQrJfyAFahgtTcF2cVmAXVrg7BBE4hGLICT9lZPCitOplUzJNrtnohmHVNQytaLXmbxx+4azkj5++mudcYZFBOTI3x7vwLNyrZCGik88CKXxjbL9sH8OAS0XpM9nSJJdyS7P3CJXrLHwPU8oQ6vsI46eWlRY3Ach5nN6fTrX4nc1bRwtBC9jg7KcfN9UyaNYo/SEHiukq7WpiDT/8pzqQGeCHziuiM7O+y9CvQjjbhQJwHyJIbXYac1s6MgOypUx9fDt3wctpSkh0cIJrICkJ3iWgT4suJFOdf5ZksTQr3O68L6/Fwq6RILX+7tsKRZnJKMMtlGPpIhmU5MHFlyJRfG/JDugqq1zfNQXAilcaOmAqWarv2dRaf2zL5cNE+dxEyKYTbGSNwOG934tX+iTcgQ8wyeT9NuWohviPtqbq8vvVWzxlCJQLu44fa/57ndsKrGUjHcK2sVwNnybbdhLOIuP42wmbDi32MIjKgnD0o4xqnDe5gwDhOJhpgJgt6ojbSAPD4yHSSCEIPhcFxMdfPlupmRsk351oAwc19vqAi7J7/oMDv996LdvXaP+tFGayiy97qUkeJ2R6qnXnzbkHuSd4f7uOkk7Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: bratislava-next-revalidate-secret
      namespace: standalone
