export { default as FacebookIcon } from './facebook.svg'
export { default as InstagramIcon } from './instagram.svg'
export { default as LinkedinIcon } from './linkedin.svg'
export { default as TiktokIcon } from './tiktok.svg'
export { default as TwitterIcon } from './twitter.svg'
export { default as YoutubeIcon } from './youtube.svg'
