export default `<?xml version="1.0" encoding="utf-8"?>
<E-form xmlns="http://schemas.gov.sk/doc/eform/form/0.1"
        xsi:schemaLocation="http://schemas.gov.sk/doc/eform/form/0.1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Meta>
    <ID>string</ID>
    <Name>string</Name>
    <Description>string</Description>
    <Gestor>string</Gestor>
    <RecipientId>string</RecipientId>
    <Version>string</Version>
    <ZepRequired>0</ZepRequired>
    <EformUuid>string</EformUuid>
    <SenderID>mailto:</SenderID>
  </Meta>
  <Body>
    <Ziadatel>
      <ZiatetelTyp>true</ZiatetelTyp>
      <Splnomocnenie>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </Splnomocnenie>
    </Ziadatel>
    <ZiadatelUdaje>
      <Nazov>string</Nazov>
      <Sidlo>string</Sidlo>
      <Mesto>
        <Code>string</Code>
        <Name>string</Name>
        <WsEnumCode>string</WsEnumCode>
      </Mesto>
      <Psc>string</Psc>
      <Ico>string</Ico>
      <Banka>string</Banka>
      <Iban>string</Iban>
      <MenoPriezvisko>string</MenoPriezvisko>
      <Email>string</Email>
      <Telefon>+6</Telefon>
    </ZiadatelUdaje>
    <TypStanovista>
      <TypStanovistaUpresnenie>Nové</TypStanovistaUpresnenie>
    </TypStanovista>
    <StanovisteInformacie>
      <MestomPonukanaDokumentacia>true</MestomPonukanaDokumentacia>
      <PopisZbernychNadob>string</PopisZbernychNadob>
      <VegetacnaStrecha>true</VegetacnaStrecha>
      <VegetacnaStena>true</VegetacnaStena>
      <SadoveUpravy>false</SadoveUpravy>
    </StanovisteInformacie>
    <MiestoUmiestnenia>
      <Kataster>string</Kataster>
      <Parcela>
        <Code>string</Code>
        <Name>string</Name>
        <WsEnumCode>string</WsEnumCode>
      </Parcela>
      <AdresaUmiestnenia>string</AdresaUmiestnenia>
      <AdresaUmiestnenia>string</AdresaUmiestnenia>
      <AdresaUmiestnenia>string</AdresaUmiestnenia>
      <Velkost>2161</Velkost>
    </MiestoUmiestnenia>
    <DovodZiadosti>
      <Zaujem>Dotáciu na kontajnerové stojisko</Zaujem>
    </DovodZiadosti>
    <Zmluva>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </Zmluva>
    <Zmluva>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </Zmluva>
    <SnimkaZMapy>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </SnimkaZMapy>
    <SnimkaZMapy>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </SnimkaZMapy>
    <SnimkaZMapy>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </SnimkaZMapy>
    <PodorysStanovista>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </PodorysStanovista>
    <PodorysStanovista>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </PodorysStanovista>
    <PodorysStanovista>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </PodorysStanovista>
    <VizualStanovista>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </VizualStanovista>
    <VizualStanovista>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </VizualStanovista>
    <VizualStanovista>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </VizualStanovista>
    <VizualStanovista>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </VizualStanovista>
    <VizualStanovista>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </VizualStanovista>
    <TechnickyVykres>
      <TechnickyVykresPrilohy>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </TechnickyVykresPrilohy>
      <TechnickyVykresPrilohy>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </TechnickyVykresPrilohy>
    </TechnickyVykres>
    <StavebnaDokumentacia>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </StavebnaDokumentacia>
    <Rozpocet>
      <RozpocetPrilohy>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </RozpocetPrilohy>
      <RozpocetPrilohy>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </RozpocetPrilohy>
      <RozpocetText>string</RozpocetText>
    </Rozpocet>
    <InePrilohy>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </InePrilohy>
    <InePrilohy>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </InePrilohy>
    <Stanovisko>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </Stanovisko>
    <Doklad>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </Doklad>
    <Doklad>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </Doklad>
    <ListVlastnictva>
      <Nazov>string</Nazov>
      <Prilozena>true</Prilozena>
    </ListVlastnictva>
    <ListVlastnictva>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </ListVlastnictva>
    <ListVlastnictva>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </ListVlastnictva>
    <ListVlastnictva>
      <Nazov>string</Nazov>
      <Prilozena>false</Prilozena>
    </ListVlastnictva>
  </Body>
</E-form>`
