---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    CONTENT_INVENTORY_API_KEY: AgAcNEPU0oZ7uZPCaqQqcqnYVAsp6/XQeanMK2VL63C6tWkLubkBUARYhp9uqr9SKL7tcaXUorqAGcU/zuD3coA3dlfP7BdZjJHA6IrVMTJArIFVzh3vBUZG8jyrxbZPd4QcSWc6RveDo0ted1CRkgmBYdgTFzz9r+WqoySb30CiyU10NpL8/6DT3mxnwkwt16NbefzgH6+u9mZ3Wl8QMD093l/bft4KR4vdRR6FP8yEcgVrtXa4JzXxmCAESxHVqPXg44QkQBxYALXYzoxyiVfeiQTIULiU3UguJg5/VGonFT+6ohoH1tihGc/tFbDQi35dW6gS9C+vRxFbIPYxES9adU4alBG0n3zC646RDExwoio+6WR+8JRovk/47bzETOaMX5A2rdHKd81s8Lc2dozlT8OS9K4ByptHfiopQuozx+v7z9+mqwRTziInjNvftuII22pQMhwIBu/8ezdALGnDs6LDzLflFfeRubu97FmB+jC/4qdeW4G/66L+T4rgqVgaWv103fZ/smTrvT0OUSJyMUVGUT4IG4ZgfRvSNqnxfI420BuerprbIZt1LlxBqYv5nDaLehMmayVpDutJBbg8cfCOnILT2xrRG25lHLJAgO4NyXahKw21g+RghhIAGl1J16XiZVzGI6UsO5Zm03VcbDJSLh/HdyYbOXG3mNnHIQnjxBrKTzZzVdUdRNvI3SaNrmb/FlnuriJpl3HzROc6XSMTjwMwC0CkuX9JTqWlOA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-content-inventory-secret
      namespace: ${NAMESPACE}
