apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: "${BUILD_REPOSITORY_NAME}"
    source: "${BUILD_REPOSITORY_NAME}"
  name: ${BUILD_REPOSITORY_NAME}-msal-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgAJcMk8xEN19JrzRqieLRGcf1jFGsb/Bu2YVM/pTG0K1Mkvcjt3kGDyocrE76j2R6dnhQVsRX6rRAianvPRMJXT5yedkRt1LoUDT1XypfmDTTtTZQfm6WkZplPkWVDdOtoOai/6vaST7MIFckuj1MEllaY7KlrcSgaGBIv4r/+VnslaBpaYOiNzqpnzWo3XdlKZ5vFhSmdwtbZ0KX9j0OHSefQho3Nui8CdSsKq1xqQNIvamRJuI7W5E0TrRrHHxBVzciVlcv1uL2t5BJWt8puWOICp9Xvmv9iFXZM3cM1jHqHENDKTVhMHP5srQl+Y6GE00m6rP930wHfASnIr+Edo0Nq3l/B5FbW8DmQrdzRq8YWYYyA2CC6f5qAwnBGL8TLuVRGQlJDiSNduI6HferQ6sfz0jPNCz9TNssmD6mK+OYVdIkY4E1J+rD7FerwBiQtXOxrxwjqm+4/fN4fhYaRRggF0HTGY+94UKE1okcDTUcCJlaoRdfWKHQMw942TFPlwAWWjxYpnNhX9QQnY0JOl8e/Xbf715PZXNWwHKVEGX21T4Z//6CvWJrKn7kacSkdsO1qKOdLlSgQC8CQTlmMKcirR4E8S58uC98Dh9LX1eoZJSkY4H0fr0uQ6eRk3WjU+pPQMxyJZxYi2dimCFM7qBxsPwvT27dzshlbK2zGavZl/67oC5wtAR7VjQlWzbFe5ZavIzE64NHZqd0zMNpG6R9SOG9HC7ayPwKpsYWICauufrxLzsBMW
  template:
    data: 
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: "${BUILD_REPOSITORY_NAME}"
        source: "${BUILD_REPOSITORY_NAME}"
      name: ${BUILD_REPOSITORY_NAME}-msal-secret
      namespace: "${NAMESPACE}"
