---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ${BUILD_REPOSITORY_NAME}-msal-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgCAiS5n3l5Yb64PGkK3UOMqwsYzWbrUqC5yOD6CIJUFA9pVJgT6VenRbirr6m2KcXQut4zOC6ZIMa/FM15Z0hMnb8+20JzAyB2PqOMiLqX5gIjS5aLzne8L99L5/Y6X82u5LnHoKYwzk8J6T53iie9EqlNMXdgQS51y9MHPpHDJhiuz3QO1gZcNfiwAtbeMfQv+1SYYhPzG1LqSHuOhFCATlNQQdfIbIDv8ZRiW3es4lk5WWhSnzj4xbpj23v3A8OR+JDzzKvhfwc+pDWFQjecAIuzzyA1bU3YIgPjsRpTCTCedxAT8Dy+YQ3jUwgXk6RQWOphQ9dbtAdabaf4kWE11f9BuE/pSqdN7DDfeck1S5l7WHWzMzcfFQpM7jqoV6GLkfkoZ31V3zeG0Y6rBPRCfdEuevZ4oIYf40NdcqkntSpL2fqvbFm0Mh9dmfvwZEIV9XaNkrwxOjn2nkv/+qTNElq2vnS98GFBVCc1Uu8A/2eRCtG/wxYInDjd9VakzM5s2wekTlrY6YwxabwHgQ9mVLTNGI+FVEvuOGrDy/3KxXhM4eTlMsVth4HDyYQriHDWRBCwCyyOL5qKINoWOxexEXoQ2d4tT0KPAxu2uDAtS2nDoS6mxeuCmx2LVTZPjzH/TWii6fCDKcF47Ns0tW9aIqFPgZrhVNN+n30Fax5yZCrJFYNc+Io9C/ln/Xh59lrzX0wd80az0xssXNnLarHmqxarAOIJPWjMEqA97CznLqQ5gCIbUKH9g
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-msal-secret
      namespace: ${NAMESPACE}
