apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: bratislava-next-starz-ecomail-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    STARZ_ECOMAIL_API_KEY: AgCXC/mtOY5I57sNMtX6dGUJU+hNBAg9PkY3VgXY5O5YG15aYa3eqeqlENJllkN/I+cZ0mHXVA/jRCVcOzMdkk3EN3SyKamtlr3jnhPmnrH+CM4xw6e4/5OGrD6i5GZBqyIrv8qN/5IbkzwjqmVWO0iFNjOblaBb8WnqhfZNJrFWzz5QOtdeWGDuqWQ3Aj6rWiS5+UM1wHiYUqgh9zcBM6iBtJxecKqoRhg7H5IWv1WU3Iqr9re2opV0cBF022jAomFGA6FQU1VvasHelcC6O64SJ2O66kjwGhip6U1nwgkXcBuL3tojgAvIXNVO4L1oNL09z1FPdfmc2379Fba1Pw3E/3w+2ErzoDpdcfwcvlXgu9fqrIHrkW22oLVCf4FdKcY7sMJ5k5uvx0cKp+mZL1Zp7kSl4tmz7rDbiLzgVh/MdOJxg2CfYsUfKTrmpcCEvwUie99LG97HtKKgPdYdQtJSJUmo62aqUH31j+aK1t+xW8Q5AgSawqEiQ9XmXA8qT04xcDWkmGKc4DSzJ7/FdYSTe+h0ueOoKG2Uk4/7DL+Tny6JmaCVY2lP1EJ9MT4utEoVoQU0bzeSgGEzqsXbvVmkPfnfqVhFmBkdTuYs6x0L9874ULlM+yNDjCKjN5UfXyXPvpzd6x9Mf7PFlCEpN1wEuH/5g0EOeEvILSFhNs+aluPVMrEHSLdydgQj5Gri3Qs/U/BN3VIszcxF5a85Mn2ewDpiK4UjvCzEa3i92S5x/VjtuVGdIUYXgvk1INnymIaAlkcXTudA223w7MNe5Q4x
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: bratislava-next-starz-ecomail-secret
      namespace: ${NAMESPACE}
