module.exports = {
  transparent: 'transparent',
  current: 'currentColor',
  white: 'rgb(var(--color-gray-0))',
  error: 'rgb(var(--error-color))',
  font: {
    DEFAULT: 'rgb(var(--font-color))',
    contrast: 'rgb(var(--font-contrast-color))',
  },
  main: {
    100: 'rgb(var(--color-main-100))',
    200: 'rgb(var(--color-main-200))',
    300: 'rgb(var(--color-main-300))',
    400: 'rgb(var(--color-main-400))',
    500: 'rgb(var(--color-main-500))',
    600: 'rgb(var(--color-main-600))',
    700: 'rgb(var(--color-main-700))',
    800: 'rgb(var(--color-main-800))',
  },
  transport: {
    100: 'rgb(var(--color-transport-100))',
    200: 'rgb(var(--color-transport-200))',
    300: 'rgb(var(--color-transport-300))',
    400: 'rgb(var(--color-transport-400))',
    500: 'rgb(var(--color-transport-500))',
    600: 'rgb(var(--color-transport-600))',
    700: 'rgb(var(--color-transport-700))',
    800: 'rgb(var(--color-transport-800))',
  },
  environment: {
    100: 'rgb(var(--color-environment-100))',
    200: 'rgb(var(--color-environment-200))',
    300: 'rgb(var(--color-environment-300))',
    400: 'rgb(var(--color-environment-400))',
    500: 'rgb(var(--color-environment-500))',
    600: 'rgb(var(--color-environment-600))',
    700: 'rgb(var(--color-environment-700))',
    800: 'rgb(var(--color-environment-800))',
  },
  social: {
    100: 'rgb(var(--color-social-100))',
    200: 'rgb(var(--color-social-200))',
    300: 'rgb(var(--color-social-300))',
    400: 'rgb(var(--color-social-400))',
    500: 'rgb(var(--color-social-500))',
    600: 'rgb(var(--color-social-600))',
    700: 'rgb(var(--color-social-700))',
    800: 'rgb(var(--color-social-800))',
  },
  education: {
    100: 'rgb(var(--color-education-100))',
    200: 'rgb(var(--color-education-200))',
    300: 'rgb(var(--color-education-300))',
    400: 'rgb(var(--color-education-400))',
    500: 'rgb(var(--color-education-500))',
    600: 'rgb(var(--color-education-600))',
    700: 'rgb(var(--color-education-700))',
    800: 'rgb(var(--color-education-800))',
  },
  culture: {
    100: 'rgb(var(--color-culture-100))',
    200: 'rgb(var(--color-culture-200))',
    300: 'rgb(var(--color-culture-300))',
    400: 'rgb(var(--color-culture-400))',
    500: 'rgb(var(--color-culture-500))',
    600: 'rgb(var(--color-culture-600))',
    700: 'rgb(var(--color-culture-700))',
    800: 'rgb(var(--color-culture-800))',
  },
  gray: {
    0: 'rgb(var(--color-gray-0))',
    50: 'rgb(var(--color-gray-50))',
    100: 'rgb(var(--color-gray-100))',
    200: 'rgb(var(--color-gray-200))',
    300: 'rgb(var(--color-gray-300))',
    400: 'rgb(var(--color-gray-400))',
    500: 'rgb(var(--color-gray-500))',
    600: 'rgb(var(--color-gray-600))',
    700: 'rgb(var(--color-gray-700))',
    800: 'rgb(var(--color-gray-800))',
  },
  success: {
    50: 'rgb(var(--color-success-50))',
    100: 'rgb(var(--color-success-100))',
    200: 'rgb(var(--color-success-200))',
    300: 'rgb(var(--color-success-300))',
    400: 'rgb(var(--color-success-400))',
    500: 'rgb(var(--color-success-500))',
    600: 'rgb(var(--color-success-600))',
    700: 'rgb(var(--color-success-700))',
    800: 'rgb(var(--color-success-800))',
  },
  negative: {
    50: 'rgb(var(--color-negative-50))',
    100: 'rgb(var(--color-negative-100))',
    200: 'rgb(var(--color-negative-200))',
    300: 'rgb(var(--color-negative-300))',
    400: 'rgb(var(--color-negative-400))',
    500: 'rgb(var(--color-negative-500))',
    600: 'rgb(var(--color-negative-600))',
    700: 'rgb(var(--color-negative-700))',
    800: 'rgb(var(--color-negative-800))',
  },
  warning: {
    50: 'rgb(var(--color-warning-50))',
    100: 'rgb(var(--color-warning-100))',
    200: 'rgb(var(--color-warning-200))',
    300: 'rgb(var(--color-warning-300))',
    400: 'rgb(var(--color-warning-400))',
    500: 'rgb(var(--color-warning-500))',
    600: 'rgb(var(--color-warning-600))',
    700: 'rgb(var(--color-warning-700))',
    800: 'rgb(var(--color-warning-800))',
  },
  category: {
    100: 'rgb(var(--color-category-100))',
    200: 'rgb(var(--color-category-200))',
    300: 'rgb(var(--color-category-300))',
    400: 'rgb(var(--color-category-400))',
    500: 'rgb(var(--color-category-500))',
    600: 'rgb(var(--color-category-600))',
    700: 'rgb(var(--color-category-700))',
    800: 'rgb(var(--color-category-800))',
  },
  background: {
    primary: 'rgb(var(--token-background-primary))',
    secondary: 'rgb(var(--token-background-secondary))',
    tertiary: 'rgb(var(--token-background-tertiary))',
    primaryInverted: 'rgb(var(--token-background-primary-inverted))',
    disabled: 'rgb(var(--token-background-disabled))',
  },
  border: {
    default: 'rgb(var(--token-border-default))',
    hover: 'rgb(var(--token-border-hover))',
    dark: 'rgb(var(--token-border-dark))',
  },
  content: {
    primary: 'rgb(var(--token-content-primary))',
    secondary: 'rgb(var(--token-content-secondary))',
    tertiary: 'rgb(var(--token-content-tertiary))',
    primaryInverted: 'rgb(var(--token-content-primary-inverted))',
    secondaryInverted: 'rgb(var(--token-content-secondary-inverted))',
    tertiaryInverted: 'rgb(var(--token-content-tertiary-inverted))',
    disabled: 'rgb(var(--token-content-disabled))',
    link: {
      default: 'rgb(var(--token-content-link-default))',
      hover: 'rgb(var(--token-content-link-hover))',
      pressed: 'rgb(var(--token-content-link-pressed))',
    },
  },
  action: {
    content: {
      default: 'rgb(var(--token-action-content-default))',
      hover: 'rgb(var(--token-action-content-hover))',
      pressed: 'rgb(var(--token-action-content-pressed))',
    },
    background: {
      default: 'rgb(var(--token-action-background-default))',
      hover: 'rgb(var(--token-action-background-hover))',
      pressed: 'rgb(var(--token-action-background-pressed))',
    },
    softBackground: {
      hover: 'rgb(var(--token-action-soft-background-hover))',
      pressed: 'rgb(var(--token-action-soft-background-pressed))',
    },
    border: {
      default: 'rgb(var(--token-action-border-default))',
      hover: 'rgb(var(--token-action-border-hover))',
      pressed: 'rgb(var(--token-action-border-pressed))',
    },
  },
}
