module.exports = {
  transparent: 'transparent',
  current: 'currentColor',
  white: 'rgb(var(--color-grey-0))',
  error: 'rgb(var(--error-color))',
  font: {
    DEFAULT: 'rgb(var(--font-color))',
    contrast: 'rgb(var(--font-contrast-color))',
  },
  main: {
    100: 'rgb(var(--color-main-100))',
    200: 'rgb(var(--color-main-200))',
    300: 'rgb(var(--color-main-300))',
    400: 'rgb(var(--color-main-400))',
    500: 'rgb(var(--color-main-500))',
    600: 'rgb(var(--color-main-600))',
    700: 'rgb(var(--color-main-700))',
    800: 'rgb(var(--color-main-800))',
  },
  transport: {
    100: 'rgb(var(--color-transport-100))',
    200: 'rgb(var(--color-transport-200))',
    300: 'rgb(var(--color-transport-300))',
    400: 'rgb(var(--color-transport-400))',
    500: 'rgb(var(--color-transport-500))',
    600: 'rgb(var(--color-transport-600))',
    700: 'rgb(var(--color-transport-700))',
    800: 'rgb(var(--color-transport-800))',
  },
  environment: {
    100: 'rgb(var(--color-environment-100))',
    200: 'rgb(var(--color-environment-200))',
    300: 'rgb(var(--color-environment-300))',
    400: 'rgb(var(--color-environment-400))',
    500: 'rgb(var(--color-environment-500))',
    600: 'rgb(var(--color-environment-600))',
    700: 'rgb(var(--color-environment-700))',
    800: 'rgb(var(--color-environment-800))',
  },
  social: {
    100: 'rgb(var(--color-social-100))',
    200: 'rgb(var(--color-social-200))',
    300: 'rgb(var(--color-social-300))',
    400: 'rgb(var(--color-social-400))',
    500: 'rgb(var(--color-social-500))',
    600: 'rgb(var(--color-social-600))',
    700: 'rgb(var(--color-social-700))',
    800: 'rgb(var(--color-social-800))',
  },
  education: {
    100: 'rgb(var(--color-education-100))',
    200: 'rgb(var(--color-education-200))',
    300: 'rgb(var(--color-education-300))',
    400: 'rgb(var(--color-education-400))',
    500: 'rgb(var(--color-education-500))',
    600: 'rgb(var(--color-education-600))',
    700: 'rgb(var(--color-education-700))',
    800: 'rgb(var(--color-education-800))',
  },
  culture: {
    100: 'rgb(var(--color-culture-100))',
    200: 'rgb(var(--color-culture-200))',
    300: 'rgb(var(--color-culture-300))',
    400: 'rgb(var(--color-culture-400))',
    500: 'rgb(var(--color-culture-500))',
    600: 'rgb(var(--color-culture-600))',
    700: 'rgb(var(--color-culture-700))',
    800: 'rgb(var(--color-culture-800))',
  },
  grey: {
    0: 'rgb(var(--color-grey-0))',
    50: 'rgb(var(--color-grey-50))',
    100: 'rgb(var(--color-grey-100))',
    200: 'rgb(var(--color-grey-200))',
    300: 'rgb(var(--color-grey-300))',
    400: 'rgb(var(--color-grey-400))',
    500: 'rgb(var(--color-grey-500))',
    600: 'rgb(var(--color-grey-600))',
    700: 'rgb(var(--color-grey-700))',
    800: 'rgb(var(--color-grey-800))',
  },
  success: {
    50: 'rgb(var(--color-success-50))',
    100: 'rgb(var(--color-success-100))',
    200: 'rgb(var(--color-success-200))',
    300: 'rgb(var(--color-success-300))',
    400: 'rgb(var(--color-success-400))',
    500: 'rgb(var(--color-success-500))',
    600: 'rgb(var(--color-success-600))',
    700: 'rgb(var(--color-success-700))',
    800: 'rgb(var(--color-success-800))',
  },
  negative: {
    50: 'rgb(var(--color-negative-50))',
    100: 'rgb(var(--color-negative-100))',
    200: 'rgb(var(--color-negative-200))',
    300: 'rgb(var(--color-negative-300))',
    400: 'rgb(var(--color-negative-400))',
    500: 'rgb(var(--color-negative-500))',
    600: 'rgb(var(--color-negative-600))',
    700: 'rgb(var(--color-negative-700))',
    800: 'rgb(var(--color-negative-800))',
  },
  warning: {
    50: 'rgb(var(--color-warning-50))',
    100: 'rgb(var(--color-warning-100))',
    200: 'rgb(var(--color-warning-200))',
    300: 'rgb(var(--color-warning-300))',
    400: 'rgb(var(--color-warning-400))',
    500: 'rgb(var(--color-warning-500))',
    600: 'rgb(var(--color-warning-600))',
    700: 'rgb(var(--color-warning-700))',
    800: 'rgb(var(--color-warning-800))',
  },
  category: {
    100: 'rgb(var(--color-category-100))',
    200: 'rgb(var(--color-category-200))',
    300: 'rgb(var(--color-category-300))',
    400: 'rgb(var(--color-category-400))',
    500: 'rgb(var(--color-category-500))',
    600: 'rgb(var(--color-category-600))',
    700: 'rgb(var(--color-category-700))',
    800: 'rgb(var(--color-category-800))',
  },
  border: {
    error: 'rgb(var(--color-border-error))',
    success: 'rgb(var(--color-border-success))',
    warning: 'rgb(var(--color-border-warning))',
    passive: {
      primary: 'rgb(var(--color-border-passive-primary))',
      secondary: 'rgb(var(--color-border-passive-secondary))',
    },
    active: {
      default: 'rgb(var(--color-border-active-default))',
      hover: 'rgb(var(--color-border-active-hover))',
      disabled: 'rgb(var(--color-border-active-disabled))',
      focused: 'rgb(var(--color-border-active-focused))',
      inverted: {
        default: 'rgb(var(--color-border-active-inverted-default))',
        hover: 'rgb(var(--color-border-active-inverted-hover))',
      },
      primary: {
        default: 'rgb(var(--color-border-active-primary-default))',
        hover: 'rgb(var(--color-border-active-primary-hover))',
        pressed: 'rgb(var(--color-border-active-primary-pressed))',
        inverted: {
          default: 'rgb(var(--color-border-active-primary-inverted-default))',
          hover: 'rgb(var(--color-border-active-primary-inverted-hover))',
          pressed: 'rgb(var(--color-border-active-primary-inverted-pressed))',
        },
      },
      secondary: {
        default: 'rgb(var(--color-border-active-secondary-default))',
        hover: 'rgb(var(--color-border-active-secondary-hover))',
        pressed: 'rgb(var(--color-border-active-secondary-pressed))',
        inverted: {
          default: 'rgb(var(--color-border-active-secondary-inverted-default))',
          hover: 'rgb(var(--color-border-active-secondary-inverted-hover))',
          pressed: 'rgb(var(--color-border-active-secondary-inverted-pressed))',
        },
      },
      tertiary: {
        default: 'rgb(var(--color-border-active-tertiary-default))',
        hover: 'rgb(var(--color-border-active-tertiary-hover))',
        pressed: 'rgb(var(--color-border-active-tertiary-pressed))',
        inverted: {
          default: 'rgb(var(--color-border-active-tertiary-inverted-default))',
          hover: 'rgb(var(--color-border-active-tertiary-inverted-hover))',
          pressed: 'rgb(var(--color-border-active-tertiary-inverted-pressed))',
        },
      },
    },
    // OLD BORDER TOKENS
    default: 'rgb(var(--token-border-default))',
    hover: 'rgb(var(--token-border-hover))',
    dark: 'rgb(var(--token-border-dark))',
  },
  background: {
    error: {
      default: 'rgb(var(--color-background-error-default))',
      hover: 'rgb(var(--color-background-error-hover))',
      pressed: 'rgb(var(--color-background-error-pressed))',
      soft: {
        default: 'rgb(var(--color-background-error-soft-default))',
        hover: 'rgb(var(--color-background-error-soft-hover))',
        pressed: 'rgb(var(--color-background-error-soft-pressed))',
      },
    },
    success: {
      default: 'rgb(var(--color-background-success-default))',
      soft: {
        default: 'rgb(var(--color-background-success-soft-default))',
      },
    },
    warning: {
      default: 'rgb(var(--color-background-warning-default))',
      soft: {
        default: 'rgb(var(--color-background-warning-soft-default))',
      },
    },
    passive: {
      base: 'rgb(var(--color-background-passive-base))',
      primary: 'rgb(var(--color-background-passive-primary))',
      secondary: 'rgb(var(--color-background-passive-secondary))',
      tertiary: 'rgb(var(--color-background-passive-tertiary))',
      inverted: {
        base: 'rgb(var(--color-background-passive-inverted-base))',
      },
    },
    active: {
      primary: {
        default: 'rgb(var(--color-background-active-primary-default))',
        hover: 'rgb(var(--color-background-active-primary-hover))',
        pressed: 'rgb(var(--color-background-active-primary-pressed))',
        inverted: {
          default: 'rgb(var(--color-background-active-primary-inverted-default))',
          hover: 'rgb(var(--color-background-active-primary-inverted-hover))',
          pressed: 'rgb(var(--color-background-active-primary-inverted-pressed))',
        },
        soft: {
          default: 'rgb(var(--color-background-active-primary-soft-default))',
          hover: 'rgb(var(--color-background-active-primary-soft-hover))',
          pressed: 'rgb(var(--color-background-active-primary-soft-pressed))',
          inverted: {
            default: 'rgb(var(--color-background-active-primary-soft-inverted-default))',
            hover: 'rgb(var(--color-background-active-primary-soft-inverted-hover))',
            pressed: 'rgb(var(--color-background-active-primary-soft-inverted-pressed))',
          },
        },
      },
      // secondary and tertiary variants are part of DS, but currently unused
    },
    // OLD BACKGROUND TOKENS
    primary: 'rgb(var(--token-background-primary))',
    secondary: 'rgb(var(--token-background-secondary))',
    tertiary: 'rgb(var(--token-background-tertiary))',
    primaryInverted: 'rgb(var(--token-background-primary-inverted))',
    disabled: 'rgb(var(--token-background-disabled))',
  },
  content: {
    error: {
      default: 'rgb(var(--color-content-error-default))',
      hover: 'rgb(var(--color-content-error-hover))',
      pressed: 'rgb(var(--color-content-error-pressed))',
    },
    warning: {
      default: 'rgb(var(--color-content-warning-default))',
    },
    success: {
      default: 'rgb(var(--color-content-success-default))',
    },
    passive: {
      primary: 'rgb(var(--color-content-passive-primary))',
      secondary: 'rgb(var(--color-content-passive-secondary))',
      tertiary: 'rgb(var(--color-content-passive-tertiary))',
      inverted: {
        primary: 'rgb(var(--color-content-passive-inverted-primary))',
        secondary: 'rgb(var(--color-content-passive-inverted-secondary))',
        tertiary: 'rgb(var(--color-content-passive-inverted-tertiary))',
      },
    },
    active: {
      primary: {
        default: 'rgb(var(--color-content-active-primary-default))',
        hover: 'rgb(var(--color-content-active-primary-hover))',
        pressed: 'rgb(var(--color-content-active-primary-pressed))',
        disabled: 'rgb(var(--color-content-active-primary-disabled))',
        inverted: {
          default: 'rgb(var(--color-content-active-primary-inverted-default))',
          hover: 'rgb(var(--color-content-active-primary-inverted-hover))',
          pressed: 'rgb(var(--color-content-active-primary-inverted-pressed))',
          disabled: 'rgb(var(--color-content-active-primary-inverted-disabled))',
        },
      },
      // secondary and tertiary variants are part of DS, but currently unused
    },
    // OLD CONTENT TOKENS
    primary: 'rgb(var(--token-content-primary))',
    secondary: 'rgb(var(--token-content-secondary))',
    tertiary: 'rgb(var(--token-content-tertiary))',
    primaryInverted: 'rgb(var(--token-content-primary-inverted))',
    secondaryInverted: 'rgb(var(--token-content-secondary-inverted))',
    tertiaryInverted: 'rgb(var(--token-content-tertiary-inverted))',
    disabled: 'rgb(var(--token-content-disabled))',
    link: {
      default: 'rgb(var(--token-content-link-default))',
      hover: 'rgb(var(--token-content-link-hover))',
      pressed: 'rgb(var(--token-content-link-pressed))',
    },
  },
  // REMAINING OLD TOKENS
  action: {
    content: {
      default: 'rgb(var(--token-action-content-default))',
      hover: 'rgb(var(--token-action-content-hover))',
      pressed: 'rgb(var(--token-action-content-pressed))',
    },
    background: {
      default: 'rgb(var(--token-action-background-default))',
      hover: 'rgb(var(--token-action-background-hover))',
      pressed: 'rgb(var(--token-action-background-pressed))',
    },
    softBackground: {
      hover: 'rgb(var(--token-action-soft-background-hover))',
      pressed: 'rgb(var(--token-action-soft-background-pressed))',
    },
    border: {
      default: 'rgb(var(--token-action-border-default))',
      hover: 'rgb(var(--token-action-border-hover))',
      pressed: 'rgb(var(--token-action-border-pressed))',
    },
  },
}
