apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCjpUp48BDtIwhl86VCckreoQCPrCVkajAlnVMWJ5rcqHPIsT6xyWbKhp67P8rtBWz7xq48axt5VN+PfH+Gs4rY2xNloTHd+TzjEQAfRXLV+Q9iN6i7J2WWiBPrMD3Yb9J9DlbFjp++HnIEFQsa7O01nXTDdhTl9wO18vS+2hYC1h28U8Asi+UF6PgTUaXXNzZWrgeXGJA4ifkaMkpqu1etF7Mf0yRKOjwaCK8c7FO3JismDrhIqJQf6nLCbuJb598E0FNu8JvQu/8l5IAoK4cbEyFICHi02XxT40wkYgv0QsTxVslFZDM59QzGmV689CKmFq8+GnmivRSbRm1WFLrJHic87pZmWYT7qSLjNl9FTNIx3j+/xYzGhsPeZRhhpTgEyBTcsu5S0BP7iA2TgzpYNgzxH/zO3BOkbrBEK+Z0QJXdbwSIRWSyYSFKK8KZrZmq3WXsRbErlb/4ijXpKzPATdQ41f+QRBgYBqhf6eFucu4sFpoVLXEJASuv5r+Ia0trYzGOAfsphdBmTejX1KDqzYQHl5CEf67ONLFpC/vz5C9/3ziW+Jq1jAlfhtklwlkMKN7KUg5xpzJhbfhZVI+YEAXQTm8gZ9K2k1py9+ckKDsogSTnLl45kVPo2JjeVZXxard2y6CKfpBCk6o1Bnxib8hWc1s8vOY8QzN6fUqsZaE8pCPMaZCFLqXsw0bE35LfzNAGvYYlFkUoXZhLyGdqioj2MdLTBu4xj43Ld2c+2fI=
    POSTGRES_PASSWORD: AgABGzD8zv+hVwXjvxTNHntjMxei8MU/mXONd1/AAdmxF+CsplPnYRftvFPTF4MXnVIyDhtZRyJz+3w2cF2xUIKFWxHOc/oZUbvTXq89MAh4hq0tm8do9tHMqxs0tgwF+W5zxea4oEt3PNyBUyRleFJCdFvDqvsvNwKMQWwycmfkhd9kcY/23d6lodL0N4iVCdzkAbRHugSxVrcEYsL73cTle8r97V4NNBPs0ZeKr/TfGhDy+FiKsnwnMkGL9wPY19einfret73Ap+LO2k4SztV3Bu07zaZiyaBRd26NKC1+zdPZ+jRbxf/NldP1CekQYFJkd0pDpYmfoX7Yk0A/m7kJmyziI3tyxEL5uAoi3sRagqMfytw21eXC9XLra5S+O1ZSwpw72PHEVAW8Emk+xNm2K8snwQhjMa9+tVZ78pxdMuhtGh7DtGGbK7/3tUC8MSq8B3n89pVGEjeDLBIqa/szUTMgyc/STyl3KSVb09B4zbSMXYX+b8VfvZTky2tWkbpOpVCKjmt18HPqteKsSnU3Kn6gijsz7XHXb6Ni7QOcXL0smF74XdBWoKpfRTlbitTh+Kd2lXUi1QI1Bbn+6jnlMcqQOcerfgWdTmj1fKmrNfYdQxapIpkRNMEkccYXoRNdEhR3C04Xdho3i9DGIYc8KQ5UWg/NSy77yAwYQWy4Mr2d+BMmy6WcaU6yB5dNSXKH7ivqCVjM45d6GPh0mb2ZEULh09M2L8ldWl4BI+FfCNw=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-database-secret
      namespace: standalone

