apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBCfDGPZ2Xd/YX8Ix1UcoQYyd8E49GItEqk35BORqVUO24KzfhU/TOcqxdpscm8AyXdhPIJDT9LVsNzY2OjNX/hQZ+Y/SF/YlRaVJBc2emNAKchHXcqKpMSGZH9iKeSCeP2J446ZawiV+4e+Jniyt/0OJaE6z9UsyYjYzKejO+8ya/7BB2rYPhrUKeYXdifzSx0OXWE8rl3PKWj6crTNbNlNDkDqJ5CHtgdZ5GPrWqEemb5hgRvGdcyTiXjYPM2a/dll0MEGMkTaSba7O5wNGbFaoed8Yq7ugb75uIheH8O1FgJGc1x/zTuQo+VFC0ujExoYmsbQGNnTVY/oHTaCxzzDsOP+T7QfXXDrHbS/3FE9ZlWm01/s4gGVfMhdKq1TzUKZA8/acyD4GCkylNwFOuoqwdRxzfyCqiMKhG5BXOKfABbJRU1d5MhkQj5KEsBQ0zgq2aA7SMsQy+/5vEz4DoR7jMO6wdCK6SduJCfyruHVSxiOoaC95ehGEko0mDU0xP7tBVWAN/1wkNfqa1dMsdJNcooLu1NYVqFnCN0sfkl3uE02qTW6S/XC+YY/dTZRwGoaXcthXPJkzpdI2qfIUDhHl5CgC4dWRoBudUMmCe4mjZTMVSHjKK4CNsVg+v1BpNTfWQlAWJQYl+uJixd6IAjAs3QULu9nVYx3Q/Q1Je4Tv1vFU8yUcZ5nvQgg7l8N2Ez+TwDj0yrojN+mku+banTXzFDzJbfJ4qQp1XBb9nQXA==
    POSTGRES_PASSWORD: AgCaj2bFszyqY0pHc3SYcimbFNZNVyj18PBeCN4BXCEjSXhQle3z3O+lBWHi4TrrC5KOzdU8J6UOP1MltGCE9sIQ7bD01qzqKwgM+biAAk8SZj3/fFj2FjnReDhc//0DTakXQriU5g/ZCtmIEBx7EPbEjSeBfZzk1STTJTb/88PBu7HZB5psG6QjSqmnJNzfrNWqg5xeXjrOR/W4BvoM0ZzHY1QZ9l/tWq9LIkHmpO/TKK/lMF4SffZtv/bE/WLLx7MBiL9ZzMKDwrBIU0XBeM0j8QStK5txrI2Gp0cWyKS1p38j3TEth6OV58wRCEW1TT1V2r+q4I1zS8AzZbnmULFaghNvbA7ngj35yKo5QjIeEZRXKWDC2RB7S3DYQp9u9XVGc/8/F+y1TjEMKe2FjSUvE9ngXBk7dAMR1ISA1kEx/V2xioIcdoWausIv6OHdQ0iT6vzLWYAQwmKwXGQAZ1+4mcqSMz1Xg0DHVWI7oKyvzvFSrOiBlPBGVoRf7BXXa3f2GZ736TRiHeka+Cf3cZuFGUfm9kQMQCRazBfFea48YHmFXRhprYoq6IlX59KXwdAJNAOGCMotn0lg629UDoLQhDdmb7c4E1YdHcvfKobeaazWsMH3x9ILtM4RgMjPxweiU3+L9AmU6dJ97qYJ2JiR159ADrv5XmDsynIRrN5RwmYIPqgKqNJlK5tgd/vDQB7oc4wpwS0rukRPAicOjFs9NgacpplS7FSamn/fC8mS+A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-database-secret
      namespace: standalone

