apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBbQvcOqeDKhDMYwH8xKug+zCkEt30YS2O9YiZj1HBU3A8nldeWIqr4wnlBKyJFeMbX+92PQ0kLzsQyvCsTslH3EHzMOe3K6krfhd2Rqn1bBsEpnUh+hpp9I4gYaJhiatFtc2JzZqJXGRXDFMq+tYhIxIL9+4mM7oOe8MZqBuCBkGHQq67cPvjLIvh8+sxVqtkjPygrcLI3if6tl66A7Ise8oxuvcgBBSzr6xgHTiTVsqVpDRdzR+awIAX5YBJ0PqOIvU1tdxFQi7+BED5YC0jz+PDUSIfwtvcepsewzyi1kueoTOcJjYJ8HWlWt5GLhGWrOxUSVN2fdHg8+xY7n5EAirD4uVpUT0copMk/NSkW8eDE3dtb8CMbupggCqEnvxzD/5fYMQeogzbu9hKsz4vcSihLPmWsKbAoCucU0oblJ3Wu/b+csNxLx2kcX0Ha69qHhDQwMLkuDEWtG3hvRKUkDsPpkJQczdl8jyz1KvSbNA1jjNuxmILhgpC+b0Q1o5IIg8Q9dOA/TkLJe6eijDF8ZQZEnlZsFgl9kp/IOAEjeOwFNuHEaxV9mEKIvyKBewsd687eKjq52gB3XAvnf1U7kTW+yZ011Bhr/vRIhEhBl1dVE4cnWUACxXv4ax+kvDUBWUqz3e7uX77fC8f/sfnN18osz980YZUPNzZWQfXRJMKF34NC4InjMdFDLvTzkPsEMAOu0fM2XQkMTY4Z+Nqf7+mUaunqvP1Yama2/g==
    POSTGRES_PASSWORD: AgAA0fwRTecD9y9Abyekk880im1tD1kgZY5DrOIp6o/OZ/pf69OMj2mCIohl9Gc+dNS5S5YIYlTb/i1lZcxgyrGazL6Hn/T8oD47qycjoos0vVJ3QINl8Yc4lRd4OjePeSi0KppztjvzFLrfJDNSjdLWap1gqtXyj2in63RKSlwMyjchDrtWpYYXTxEapQQJ7SXjt0UPra8VmvC3wMRbKHOnDk/YHKIATePC4nayEgBbfzhIsVmY/Tr9HbBrTtwSUOt7G3JoYj17PPIK7GxC300f1XzgJ96jwjwK/nRrGIU2hiLMYJD1vr34suoUppCQ+JUpoY0sFb6IQdrrkS8zKgKD7PoeJjGZTk2l8xHlxB/jqi80LvxwJZxXvbRH8cEcIcewixGBTm/9Vk5UP97vsJeu6iRt14BpiD4IjmCymqJfJUP58pKOqaXjU59IMpKxq1HCDDx7v+8feT7NR4dV10N6hzJExna8Z96IpkneVuKnqm/dSLYeH7PPNzL0H9oeW5xonGC/yjia0u4haSyOfjAvnywAO3DG+jm6u+Q5TfFTN+iyEtXMulHRfH4Z7C8Np9WkIIbq80dHfl8IsZvgZypS3Rc6AO0XCD0LXXR8a8AoFc/BgUguV8XEZU36nKZtNyYnlgTKrpgkXIWrza0rJz4qGtx0KMWiHNr0gdrk8sbh3n0mzUpV67mKvqQCdAZ1cIsCUEes2ObAPU08c6CyJJnwUU1a1cFwxnwL1JtVVw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-database-secret
      namespace: standalone

