apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgA4fboYwHFgWXwtoasS5PwFfn5f6pzPo+RA/L9uSulFb+DGZMpudPSgHgkAgCfTq59nCcm6Hx4X70xbV7GMRbRoy2txUxYFcAKIRG2BNWwR9+5i6oUVxqM92qjFmDzHWOxR6oWde8f17stamHoCAPYqjbkh0wJimnYWLxjYF0OOyyrxr49keXPAyc45AF7tqZI7iKwjvW5mIKV3KHaSF6RAjtiiyxlLLb3Ux/R9q2nZVAI9/xFV3Tz8IvfIsZA2n2OkQM7X3GBDssiQLRNjTPj/l9us9uEiO94jX3+YmJo8LgQecRpTN20wSHUxIabT1MHEHZ6hUi3nfPuXPNPfjBfAZcUx1bB5IYrQXCMe4ZiwmZDOQ/UiWtFFnE7WWsQuTkTHaJpIUu5yh6vlDhDLBwPK/JOsXDfqdQkHeJ3hJ6e7aTOaum7kBTwp/7hxcyVoXYkS+TfJHMPhwWdYUTdO9a7sRfo0lELb42qW0h06gjujgMeIPnCQ+OCeiMKe3jEaL2wXBaPU9uVb+oX3JJpk8LrVxaodWboa5nc/CxqcbwDk3wSzwkngXrjvUzdLnRulzVT4asD2zF7VKVkcOD+vhbiSBWMuNJ+t1mkWRDygJ0fqgcgHvRBPTi+gI8+Mw4yioq32W9+EEaCS1nV3L99reXy+YAjt9VuRQpF4T/b8batMHPkoqau0pNxg5tXUiuWZ0U+xyrxAkmqDS6pfrtCwsm+FPWQb42dSkvC1YtI=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-meilisearch-secret
      namespace: standalone

