apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgALkEB5rh/jUO3N1hlFkUthrCWpYdSzrH4D+hFQxh1s5IJsaXORBGdCxzDDN0SZRaYzBOkV7QXGZk4NgNdldG84ZifLCit0XXEy3N5QfVzEOMvhK8vf9WVVU276svpIevc+R//Qdrx7zBETe1PdWVaVv/ipHIX6xdiM+YVw6il4WskCs3AP/7MBSKZLxcLdkLcFfyac/xcE1hzg0iZUwJwWtDt8/M2u7m1l8be15QpugfjlHsUzjZ5kw1IcWYYDt8XKK+OqSNkjrJc6QOpxlTRwjIwEMM5W1FJi2PNWdOA2RezIYxNeSSDv3Giw59VQczSVgPu57QpyADxGGJoBOrLgd6JRZv/Zv8V1AeK6N8bBat4oHNYxYq7FT9blrG/ZDyILK68r0F5TA3PTaJRIV/o4sc6jOYCF5u7cr3Sd7QSz6tAlt1nZDMBZuf5P1RUpaFgB6gjvbIRafAgxeIxzFrO+R9wnVv1jGru+8CFdPKD/C91RxQfuUvPoj6UXZiLcHrOwmzuyeQN92fLL80q890YBT4BTfIw6zORy/GCctfz9G8fjL0glw3XTcyR2brYJzt9pTNsQKXWGWrmJ2R44OxxHYhQveEYW0pB5vUtgG9cdhE3hfPsarLNtxm+gze5pu6v6FbUZIfSeYnXuL1ayKslIMVBklcdL9pcIicYphYJecpbUcg5cX3lniVi9Z2TyFlFrsDKANPmyiFt3H4f69f7O7Q8pPsooLqXBbNYauBJWg3FfvQZnhE3l4bk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-meilisearch-secret
      namespace: standalone

