apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgB4a1stgepA65CFMEI+yr6UHRqrENGQvXfsRVLCYs1GdxJhlG0ZUe2tk458iKn3ocFUWsU403wvVBbOf1cVVRVROKyerlqCd4X3JAAFRuqF8H+B0RQJQMDG8rO7k8QRTz4YSayCG9xgpY643TNshmvEebhcMY3pgp6EDsjIR47lx/IYHU+PHr40xxn11n01DaZ+QLo8q6n+42400JfyKgNzVHpt+HUcebNo5elAFn5J7g7G96l/pl9n/NPT+iBzNOL/uz7/3gJ9tlmRRP8vtMBLA7YxQFxQBzdT8eFcTCKtKBV7DxmLB+v/wofzPLG9FDVOcaByL62JPEDixgD4AT2LdhMg5sdfELJz8EUdNl/K8JO/sDWJB9qlZ/akDaQMrMMYCUqtkzBJpyUpVmFXJJ9bFoJ7A1eqxZhWIPrUpa9GXwu48gXuKBd19jaA5MjoWOP1NseWIU6c9PQvZRBYsc8H6guPs6dlaUlRWYFOEJ9yORRn/XJIsvQFaHoTjQgwShrDT/brN9YWTgoZDGMN7xJRhTkkbaDuyf8AdcSqyoeStJsrCVqFp3lfZCLKBBJ5v+KLUw16SlwiR90CbH3XPfQN0v/H/qZ5sj3ln8SzkkETNHXGYOcjtDuBGzhEyC6pNHttKVTkYmCv/ecxznDgWKNOgoxJfmMa65zzQnXy4SD8vPqmXCsivxjwpf3Nb7WZEylbxSLOv2T3s+Z6yEaqTYUAUUF1LRHOIQS+tRH2kPvikNAdWnA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-strapi-meilisearch-secret
      namespace: standalone

