apiVersion: v1
kind: Secret
metadata:
  name: bratislava-strapi-internals-secret
data:
  ADMIN_JWT_SECRET: YmFuYW5h
  API_TOKEN_SALT: YmFuYW5h
  APP_KEYS: YmFuYW5h
  JWT_SECRET: YmFuYW5h

#
# Run this commands in terminal to generate the above secrets:

# Generate 4 random base64 strings for APP_KEYS - need to be encoded in base64 together once more:
# echo APP_KEYS: $(openssl rand -base64 32),$(openssl rand -base64 32),$(openssl rand -base64 32),$(openssl rand -base64 32)

# Generate base64 strings for the other secrets, encoded:
# echo ADMIN_JWT_SECRET: $(openssl base64 <<< $(openssl rand -base64 32))
# echo API_TOKEN_SALT: $(openssl base64 <<< $(openssl rand -base64 32))
# echo JWT_SECRET: $(openssl base64 <<< $(openssl rand -base64 32))
