query RegulationsStaticPaths($limit: Int = -1) {
  regulations(sort: "updatedAt:desc", pagination: { limit: $limit }) {
    documentId
    slug
  }
}

query RegulationBySlug($slug: String) {
  regulations(filters: { slug: { eq: $slug } }) {
    ...RegulationEntity
  }
}

fragment RegulationSlugEntity on Regulation {
  documentId
  slug
  titleText
}

fragment RegulationEntity on Regulation {
  ...RegulationSlugEntity
  regNumber
  fullTitle
  effectiveFrom
  category
  isFullTextRegulation
  mainDocument {
    ...UploadFileEntity
  }
  attachments {
    ...UploadFileEntity
  }
  amendments {
    documentId
    regNumber
    slug
    effectiveFrom
    isFullTextRegulation
    attachments {
      ...UploadFileEntity
    }
  }
  amending {
    documentId
    regNumber
    slug
    effectiveFrom
    cancellation {
      documentId
      regNumber
      slug
      effectiveFrom
    }
    amending {
      documentId
      regNumber
      slug
      cancellation {
        documentId
        regNumber
        slug
        effectiveFrom
      }
    }
  }
  cancellation {
    documentId
    regNumber
    slug
    effectiveFrom
  }
  cancelling {
    documentId
    regNumber
    slug
    effectiveFrom
  }
}
