export { default as AddressIcon } from './adresa.svg'
export { default as BratislavaLogoSvg } from './bratislava-logo.svg'
export { default as EmailIcon } from './e-mail.svg'
export { default as EuFlagSvg } from './eu-flag.svg'
export { default as WebIcon } from './web.svg'
