apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAtaN9JM7yq6olqZFRmoHfRaOVtVEMVv25qaf9GccWn41euKB7Frft76FRHMr4msBjDe+nARaHvpxfvvB5LcQZRgNKKoR7Qd4pd9y9xfphV56u+dLqCBj2VdFxO7FBw8+mqNAIb7jIq9zvT9M3rfndltkXLT1mq1PGqQEmHYNBI0cl2tGWkOd3KZHuA/OAVAg14AcWDFrhOS/7NDK3lKBRtZF1UhiWU//9C6NfU3VnBHIDpGGpJd9UAee3Fgy286NPvuxihCjO6wpJltMgouhdGsqRs0PhYl9rxj1k3XQSooZ0tNhvAHu+BODS2yKjZLzw4RL3m37IrBJaK0LnsiAW4jcUBYHjIAcQRdcGOoq4L7uh7IUAQnBA2tmqdnGwrBBL460zQxRp0gZ25W17kSAGKdxdpbOacDYi+iI/ZaULjetw1fQMvYaXD9oAJNXlsisYjArnWBjHZOor03P1199BMKOXaU8vBh91l+fr7TMstmR3WSZymFkTSSGK2McuIXD4S3xehEzlpKAbmc1P7E53Epxu0/zo8tH9/MSFCsx22RAOvgON5nyTZ4URxjpBFpCOBgeb3IPPbmEG9uf1aL2P8HMtGKHQC8HTd+DyIFmHgEH0JGAk9K4/y18ja1uOKoVx5cWEI0TCDoWVITdaV4Un75xFfDz8e5V6WDD8u7uYkIqZpVyz12khXunNXJkOUMS63FhTrLjKitUEQBJikFA9ZjxpN/NVI/SxggUPvgtqkDvWbX+WpE257lzAgzWfJoy6GWg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
