apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgDFmWfs5iJZU4VDjf2Bc2U8XlnHemCYnkULRyiYp1gjls9o4JQR6apJ4gwKjBWirq/fm6UNmiKgxHMEcW7aFtzVfuwtg4TSd+NOxPvKs9OIkxXphOY98EixuhsbjiWBUNeES//z2WpSfPj6S7/Zei9MeHlo74w4YL5mavUd3h9hBjqvHabXJCSXlKx5YHAF0DsANZOOTOzPkOIms4VMeQD8M3cU1bukTaV1xdk6BrUJCiufCpU/ZPANucZ+8ZAskYg5GoP7VLNFx4QBg6X+Me0YF/DPEnFhXLj5hxTFB/rBzK+hP6B1TucLnRWpvBq7cJMw8DQulIMmURwvjlx8gioOxvOhQoOjMDEx6RYm1vEosdt+eZmBtP95EXtTDG4ul8CG582xmKp06OdZ4buRB6pvhGY4dq52k+Uan0CNKbZSK9qpoUfNYcuBMIm7Fp2HrU+EX3YwBN+McAmHQScOKhw1KKhv1na6o6+6H7RDXSOBQO5RMWpx35dob8vyMOukkyqDdNKRPSYBES1gxdA5zGLjVxfJHlb0Xb2ye0VcHBJjA36HTbl+/E8O7kqj6mitOm0iN+ARKlyTsOI/YaxsrHAm6X3Ycr+IljiTGbF7A6Bv7vvDbjATwTV6EBBmBYoaYJnazaGRwDaVsbdEOK/iYuX1oMDssxxqiFEIv8sZnaptCbOa8gcYutwOEnstt8SS2Bu4T0FgcTSzeHAsGyGxlXCqBedwdg0wsCx8poD6A7x++pOuMAikKldtW6vkQqCBtp2e1jXsMks7p2IwxVdY++CK
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
