apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBCrgq+szeTcUXSa6Iww/mWHXhiIEUHMDVjkiGJ8Y66rC3bME8sY6eh60t+M89AHE5K36cZvQJQnOD0HGV6zYSX1lne0ABFCx6Yk7OIzHV4ags3/4g95E0tFN7o9nShXyNfs43X33G9xvXp3nTbXymCj9wISlcIIbajYI6xESnREf7AiLy74twwKUqXWGuVsK0Z+Z55be++HdaBt1W5HxyLDcxN3Uz95/vverg87gLb4RM/xVM+GlTkUOPeaNdlxMj7bbxbY6jJttMouoarC0TrRHpcG3i0L9CLQv1rngL0rruyxLconYPDD+W1hB8xc/BEqN9n5IEvcUY2gVVjvNZYTfb135sVqiblyEadmDPQGfA7gXXW7y8oC3QwfX+j3NrQvb3e/QZYgi7/s0+JousUrzhURSv/2s7J+b71sqsXQUJHR3o+74L226THclQyljPx3VoU+W5kQBKas2SY07YxHCihqCy+JQA5EG+HMSg6NFhsgrfa2qYiu3984EfSnvGW/Oc9/MFuNufAaTxaGMzfnQP4DKrBeOsQZPlE7MvdAk0SFaGw/8bMoWKhE3Il6N0oJPr/sl9XG0WXv0I/VYlpRAH2o/Y+iccZcqw3sODxB/w4mIhjBVjt37HI7uuQ5QTUKR12dYGCQ6y9+N6CJa5Ikg7tqT1aa/5BOOYnjwhSZO7iw3Ne/UDxVXzl/thqdns7bNabCsR24ZmVgvSOx6nqNRG2CtlogZO/lZkoen/sZnNjodkxU/losM7OYR2HtL8e3Y/yXFLJzQHRttSe0dm11mA2Ab4JjgOTWuUfFNrvd9ee5SBMyt0RLw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
