apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAquCIiXSR2JoxsMregGZ39JToqLP9cUIe7F/WJ0R3/sUt0Kt8vNXkLVLXfrct4tp/EddLgmEUYiYGDoEyDiR4XUwVE/JujVGtjj5Oa+pN21n9F5aQZ1WNyPcmnlP+efiulGg/snC18Ue++ONSnUZIp6kl22+uqGJFtNKECVBKX2nw3J7BefFfvBsaGlXPLZspWtVfIjucEwITOjmhPwh2ePHjGrTgFniBZLYR6nyQLa6bGTBdHBivXVMfLLVW2BQlmCwXhANvwDdgm/gIdryzGy/XTHRVsRD2gxBl7L30ey9Z2yzM46YhVeJqkvGfRH9VzFr3PsZS35otD0f5Af2LH8HHQKPJNkUy02fuj122ZvDH93jrn+YKh44PtGznnmf+HmwuIYmJpR8yIyOeMd57UgjO/U2+nS3dSnSjLsde+gs0t9FO/g9g/ia31RFmW4L0Wb7A3F5Ml7FeY0IaHCrhsGUH9dvaFz64BaMhyrLxDT7/BzNiopgvMbRmWTN2h41AlVaYoW5JN4MvCJLPjvYGWuOx95yA6iZOnyqORmyUnP4xOIdIspdPaRsuO2BInMe6/ZikJiKUV8VaqlKR6aUtEpeorfGSjt1FPZ0CWnQl63M2I2cbkQpmPXlY2ioHTu9e2dw8B5h0yzmqwOK2WBK1DnV9rhLN64JG7XgvPhHBmLPtOt6/D5mFFE7cEt9DhS5eAOlzknzhwkLS2GTo=
    MINIO_SECRET_KEY: AgDOlDs1nUx3fo2kkNVi5VbV+2A+lir5WF2AgpDE8bIqJEFFDnvtG4yQ+2s+j/9xUEse2fNYL1kI8brii56kWJKspScQjYWQhg39fqthfC3FcGgb7pD1TbT+XBQpOMAqsEWGR5dRsa0A4zzebAGyI3uXgWV3xJbRI249ihqz7SxXI77FIsuBpcKFewiLHIsQ5BJ9DsMnEOhWd17EAH9B7HwWLCUNFXERK72QateXsvAtIt/9OTS4ZJUIJaL/sGb019rZhiZgxrp255hNnuj0Is22klR98seInotXPBWj7nXm9TdbzUnZsnXmknfeVjfoNggGR+QlXxdgGU4bRpZ4l/p4g9U5Hmte7vFdPoJuJAxekMw35LsUgM5nb1l5nE0uPTj6B3GjHqcpZ/UE7dBWE7tDsIJLZCKqi2Z89fz4GZeFWxX+kJ+upUmz3zz1DMLKviD7PH108IJsla81R51k0ztl7zfgpgN3FAf5uSRnAs0qFw4fqv/d7ulI69Z0R+1lZ0qBZzWYZe05Gh/zuz9iuhlZJjpK9oOnvcDElzt0qFGLVnELUs8+mjAWuketC9ko/AhvcfYheIE6Pl0OonwDndkmmcnMAowZU32DYSWSzuYDg7L2IKdqvtNpLFlmfRbasNdoh0AGyYt8tqFjMnCz/cDKlnOqgZkDxLIm2o30tGwL3+WT+vB/8Y5QHb+V+lsFrK22cH4cSyosAgSBlsdljt/f+yTMpysPdDFQJ3HlFtAaQ4YV1IwhEPZWgT/vdliz1Q9lu0z5lNpDXpEd2I8QpXX8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
