apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAquCIiXSR2JoxsMregGZ39JToqLP9cUIe7F/WJ0R3/sUt0Kt8vNXkLVLXfrct4tp/EddLgmEUYiYGDoEyDiR4XUwVE/JujVGtjj5Oa+pN21n9F5aQZ1WNyPcmnlP+efiulGg/snC18Ue++ONSnUZIp6kl22+uqGJFtNKECVBKX2nw3J7BefFfvBsaGlXPLZspWtVfIjucEwITOjmhPwh2ePHjGrTgFniBZLYR6nyQLa6bGTBdHBivXVMfLLVW2BQlmCwXhANvwDdgm/gIdryzGy/XTHRVsRD2gxBl7L30ey9Z2yzM46YhVeJqkvGfRH9VzFr3PsZS35otD0f5Af2LH8HHQKPJNkUy02fuj122ZvDH93jrn+YKh44PtGznnmf+HmwuIYmJpR8yIyOeMd57UgjO/U2+nS3dSnSjLsde+gs0t9FO/g9g/ia31RFmW4L0Wb7A3F5Ml7FeY0IaHCrhsGUH9dvaFz64BaMhyrLxDT7/BzNiopgvMbRmWTN2h41AlVaYoW5JN4MvCJLPjvYGWuOx95yA6iZOnyqORmyUnP4xOIdIspdPaRsuO2BInMe6/ZikJiKUV8VaqlKR6aUtEpeorfGSjt1FPZ0CWnQl63M2I2cbkQpmPXlY2ioHTu9e2dw8B5h0yzmqwOK2WBK1DnV9rhLN64JG7XgvPhHBmLPtOt6/D5mFFE7cEt9DhS5eAOlzknzhwkLS2GTo=
    MINIO_SECRET_KEY: AgCLz4XMujY4lw5NYq1jRcX5413F2TNMJgP/Q7w61baCJvk6KE/jauN02ks/KZAuRJ1ngWC/OoodhCcoArjd/mnXisjaBbiKu/fjQbW+WrP1wMANWF/R4fR62xhVWEx6fve9o1f4X2T9saxVhQ/NcNX6wSLKxBFiEOSBPybKB4jtps9wXcUCphT9NL0xcPnbKAJ0NrDLDrVRD8XG1IFOheGLJk2E57FkV8ZZi3XG7cThP/exqoYXwhsTwg+3Fcw6wm9fCWfypgrIRLs5byfGT41sEj0cPFrYSmcP4U32I/GcSnrWUp11D8oNVxaeVz81Meu3ebj8tJbofRu/vcoglsk7spq1y8xmNw4oNv3f0OrrtH+eFGfXs2TRbyxob/xD/SaYOFlT0PoK69yTx9tBaoAoQNlp6gZV3IHvjRI2QsSyBCHofPBLZhPoTjCidkblG+OB0LTaGLeNBEuaDelR1qBA4kI1qtTDoyYplj0MLbA+oaIYshzdmXvpGgQ+WbiNffN1T1NOGgpgAIl9PPidcbrKITQCHDLC1mAtV6LsZe8XUzdJ5JgHMoazPOWnDUOth69LMOhTWB+KIeQxyBPxHBYZ2v5yEMVf0MYbAAAkUk5V5fveyXV08kOyf0dO5Opj+T7RdWniHLUhiqxU60zqPfMzOVLS1ZrlnRpg70bp9RPQ4PYGw+i8uIOBrwChQMfsrm5rdR8HiPSA7+4O8cSNdr1qiI+GFwldUYScNswBFUvqstTQubEbR1LbGB30jw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
