export default `<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<E-form xmlns="http://schemas.gov.sk/doc/eform/form/0.1" xsi:schemaLocation="http://schemas.gov.sk/doc/eform/form/0.1 schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Meta>
    <ID>string</ID>
    <Name>string</Name>
    <Description>string</Description>
    <Gestor>string</Gestor>
    <RecipientId>string</RecipientId>
    <Version>string</Version>
    <ZepRequired>0</ZepRequired>
    <EformUuid>string</EformUuid>
    <SenderID>mailto:</SenderID>
  </Meta>
  <Body>
    <Ziadatel>
      <ZiatetelTyp>Právnicka osoba</ZiatetelTyp>
      <ZiadatelObchodneMeno>string</ZiadatelObchodneMeno>
      <ZiadatelIco>966</ZiadatelIco>
      <ZiadatelAdresaPobytu>string</ZiadatelAdresaPobytu>
      <ZiadatelMiestoPodnikania>string</ZiadatelMiestoPodnikania>
      <ZiadatelMesto>
        <Code>string</Code>
        <Name>string</Name>
        <WsEnumCode>string</WsEnumCode>
      </ZiadatelMesto>
      <ZiadatelPsc>string</ZiadatelPsc>
      <ZiadatelTelefon>+5</ZiadatelTelefon>
    </Ziadatel>
    <Investor>
      <InvestorZiadatelom>false</InvestorZiadatelom>
      <Splnomocnenie>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </Splnomocnenie>
      <Splnomocnenie>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </Splnomocnenie>
      <InvestorTyp>Fyzická osoba - podnikateľ</InvestorTyp>
      <InvestorAdresaSidla>string</InvestorAdresaSidla>
      <InvestorMesto>
        <Code>string</Code>
        <Name>string</Name>
        <WsEnumCode>string</WsEnumCode>
      </InvestorMesto>
      <InvestorPsc>string</InvestorPsc>
      <InvestorKontaktnaOsoba>string</InvestorKontaktnaOsoba>
      <InvestorTelefon>004</InvestorTelefon>
    </Investor>
    <Projektant>
      <ProjektantMenoPriezvisko>8C </ProjektantMenoPriezvisko>
      <ProjektantEmail>string</ProjektantEmail>
      <ProjektantTelefon>00393</ProjektantTelefon>
      <AutorizacneOsvedcenie>string</AutorizacneOsvedcenie>
      <DatumSpracovania>1987-03-17</DatumSpracovania>
    </Projektant>
    <Stavba>
      <StavbaNazov>string</StavbaNazov>
      <StavbaDruh>Rodinný dom</StavbaDruh>
      <StavbaUlica>string</StavbaUlica>
      <StavbaParcela>string</StavbaParcela>
      <StavbaKataster>string</StavbaKataster>
      <StavbaKataster>string</StavbaKataster>
    </Stavba>
    <Konanie>
      <KonanieTyp>Územné konanie</KonanieTyp>
      <StavbaFotodokumentacia>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </StavbaFotodokumentacia>
      <StavbaPisomnosti>
        <Nazov>string</Nazov>
        <Prilozena>1</Prilozena>
      </StavbaPisomnosti>
    </Konanie>
    <Prilohy>
      <ProjektovaDokumentacia>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </ProjektovaDokumentacia>
      <ProjektovaDokumentacia>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </ProjektovaDokumentacia>
      <ProjektovaDokumentacia>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </ProjektovaDokumentacia>
      <ProjektovaDokumentacia>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </ProjektovaDokumentacia>
      <Vykresy>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </Vykresy>
      <Vykresy>
        <Nazov>string</Nazov>
        <Prilozena>false</Prilozena>
      </Vykresy>
      <UlicnyPohlad>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </UlicnyPohlad>
      <UlicnyPohlad>
        <Nazov>string</Nazov>
        <Prilozena>1</Prilozena>
      </UlicnyPohlad>
      <UlicnyPohlad>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </UlicnyPohlad>
      <PodzemnePodlazie>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </PodzemnePodlazie>
      <PodzemnePodlazie>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </PodzemnePodlazie>
      <PodzemnePodlazie>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </PodzemnePodlazie>
      <VyjadrenieUradu>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </VyjadrenieUradu>
      <VyjadrenieUradu>
        <Nazov>string</Nazov>
        <Prilozena>1</Prilozena>
      </VyjadrenieUradu>
      <VyjadrenieUradu>
        <Nazov>string</Nazov>
        <Prilozena>true</Prilozena>
      </VyjadrenieUradu>
      <VyjadrenieUradu>
        <Nazov>string</Nazov>
        <Prilozena>0</Prilozena>
      </VyjadrenieUradu>
    </Prilohy>
  </Body>
</E-form>`
