apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCkunBNvPBi9vC9usLb3+INNDgPut2heb6SO3CTJqWKtySxj/lHVmHxEZCP0uHAc/+0zaQHjAop/9O79La2oVAydu0QW5fJfPpXvVLIwXpA0/Ivj480wU7NoyhP3aKxJV4oyULTtkhFJd6zCBTisfSetj2ulq/PlIXOsLXR3ZpCuZYPkLuDfE9mMzwxnmuxTLkXPr/GTUopmSdNAWceAnKjsa9qk91TG4odIdohCZ1E42jTL+A8gff5+UyXXSlFJ2AXt40O1zuTHtomVygjbN4JqXYFo77XsOGM4NJyTaQ4dGnEtMHRsmUCf9ZI8mBIpwvvAfc4r41L1XJ0hyE0jmBFYmfovSV8MFpYJwGRoHaFPyORrUeyDcLvfWK0k+ZytVaHh8n6IXmosDJ59vqL3yj9VKyqXhHE5nWj6k8G5Ed5NMSVDwoqwkFzoVeORJK1dciOTMH+VpqUT1D0VPoDBpSrwL0lYjaV+BY5PLqwlA2t7a63+2Vj2+efnwkmGwNHsNxOxSjkC0vfVhBpomFtrExroyhSKr5fgnil5H6ZTWfZ0j2YQDjeZq/9g9jNKC1xyUh4vScw2wG5dCcuvqmg4KSBT4Qssk3XCpDtgVoV1GcWCFsPVxY4jzXNS4msVLzEgp/f4d5x9Fiwz4tXlKcQvQlxksZll5mRYcDv6xe+5Sx4bsrd6MntA7cxjvomFuokUesnZGk4SpfYpUB515BTIuHeE0QzgokEwSpRWZdXlVe463yqjiSKUS+HnhYoig==
    POSTGRES_PASSWORD: AgAbk0y/oUY0v46HmEGLFgN+rwi2r8wVyWA2Wq3DSj0CHmV4Evze95Hbeh9Qq9oAnMsRiSMpkxcL9stbvg/QTCZyF6n/As211ojUtXRzjgNStpKqh5nEPyh99txMIy/psF/mE/lXX4fXMc93sI78AjhQ43iEqkRIu8RiMv0mEYszJ9KjeIia32h/3j1Wb1+g+snR4ygLiUagLYHe5zXtHDbIDTANLXcA+kXnx5OfnBj92CqWL5pvvf8Kw0vPhydDkJkBlPV7WfiUhgOCM3cVNW9BU14y5RKRtxZ+Jm91kR3BGeiwfRW7eR1cIjnMc3U+Uex4G86llHV7vOYrt89eCA5wi12Gdgyt3K1XV5GSU9p0RDJILqP+/6tDY46M9O5BRMK5S/AZ2XZUdhF6JdNaCCogk+5N17QuTYHG3gyxP1MHJMKJyk2uhzAzUslcoi9FPs8LBJKRVgTxxcDGoawp8my75R8p9SF6WKHgPqZVVsGGjQj4PUkwUtRuESPQrj5aB47ANMGaDd09IZx8ln8nDJijfH5FIkmfcLekKgtvu380SqC8/JL3DKfbr0U4RlPtlGCCA/ekhh1sBBxj4goEqX9k3CIAoBcFNXmgzbiOkp14c+Nn/yaIjdOMMuNKveqznr8xVC6/3sfRPAE3Vo+hdb7ym0hZHcaO2cFvPxXUtGZ62TgARSWgEJECCKJD5mk50ZFNFfqqf365yUbfjAx5uiEEDmxdu/0m4P2215E8q/npABjLdBfasbKBQgvhPw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
