apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgA0asTycRCRQEsmqs3ecBXo3RpYZWRY3Wo80fG71f6RgwC87P5B6x3qR020mX/kOxuu7ZJZbD3MU0E+8nni+v+m1KbJ94P/nOGr41eKtY6DFb8pXEl87JZXx7AU04fTDRQ3vcBqCDl85S/qZHYLrxDVQK+8TVnIVpWpt6cwZHfIo8SdKaToHCJaC2EEkvQzR+ej9SRMs7Uv7FVa1vmdZ9pfSLvPkQiY0GHUR1QkwexioDIGm4pJr1cpSoHaI9rAfZEtrwosJRFifeih8cWEG+j8iFLFcQ+cKe6bAod7y2yYJWNhMUpFuaYy66lzCSi1Mlf+HFNXBEDAQiJtTgsRVRablLjJ7C/W5okLGQNTzPtrjRZN62IwPTSHCk+GcKzEVMtkhNh9pgo7adlUS+enxhdC2WrENQpCfADeo1xM44o5ojI69sbBDRF819RPd6n1N9pTc4Iva1uo4vweGacmV7ERH8ZLTjNRrgqAkz95A09VPR4Ay4NEL6DMVHoXNRbJWJewJvhyAr1hTkwSHOpRE5rDdyIS+O11T8TM6fL84ZA57DTwIIeu4T5Pb0jEXE6BbDsBT76ZLRpdP/7aQ0ureQ9Saqm10tIcUcynndSlsTzJOVHr7S5Yb8L8DDVyCqnnGB7w3e4/t2nBl93WckM+zwFxrUShBJlnje6JaeI9PutL8sTBVjabXQIIk4C2LBSgfMvUMy6QtXRbfHdiXOQwNOQXUcsX+pFENU3xLwLxpSLfrjXKZtfU3q0go0Qin8OD9riYPw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
