apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBXkKr9waZIxqUnzt2kV4ihg3MOkuzPGQfonFZ1+h1pFdzZpOzLgiDJtSu0bDspXhByC4nakxQDBaw6Rr/mqAjnvCKAPEjkt0cwMwpytuPRAy4NsLO5gQ47rZdJXWyCO4t+aOGrELFasHZT/vfGZSfrJtbvUc1PHsGuSzcUMfCFFQ23ZoIupgiX0G/DV38ndBFgEjk0+lDFqryl8f3yhX68For4fa9vn1mLZDUAjHuS7AUuWI9QdwRDh5X2qNBBCukjDwRRRQJNm+JTVoHHKrpuPrvsR3aPNID/8HwuTOJfGu6qzZ0fGqPq7q8oXpERWvVcqLfq0SFuVVoQ7m41uovvBWKTQXwcosqB3anNSokDSnwBuhbt3GTCZCxSjIbbjheuAIPtmP7ZEygS4QaFcwW9wtiAZ9Bo8iGmDr8b7eka+QrJOaW+mHJhpa/wGEyyorJyZAkXUXj1CCXumTm5AQhhc7jVCJhNM8gTOPlpXajQmPcDdxl3bAsxe10SdvTfVr50ADqlknVCh+zeXvkWICM4irsS/iW6Pp13A+miMFVhbmCqBIw5vYKpEmoApcBDtqFISgZXhTlp0X+e9gURk523PGnDp040akQIlFd4HNLafZjC2UoxkJ+Ur5biw5frIchgVvu3gxIECN3vuxqV3ACSdwpKfW6S7EyDrz+zmKH2rT0AfzPJeYeYbpR9L+EiH8v4qgJxcqI7PBuH/zDEbMQeiV3sztyhv1vTZndeWq4BdulB62FjrEFBBE82jm/qnZZCP1fief5FpI9Hs8hwaiWeG3ytM34+Q8SsRt06ho461/VtX9fYGBXwNw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
