apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgA8XSkcAoSb1EmpXnMnvhP+RwWOyxnAxbjhq0/2+reyXFP89FqVqTfkd/uITTsKkYxRyhwjiKNvVKpa11CrLTiYBvQ2MbHYcvoBDmlctNs0UcgyQ9pEc/ZJs1oN/+1px21bxe6eg2eDUebbr+UHN409v+ZTrJrSfz0AHS6S32YJ5MZcrZHKiLRiLPpW6qrb/TChv6++JeBJ4cGNbAKLZ8H89LWLO0PE6NLlPA0PtEIpW2MEUFjXECgUUS+kH2GQflQhMSBFUtyVlKbH7kBSrJn2KNtO5RuftY4NqYZr/eljnl6VMANe06tYVP3O2fb2KzV5C2AGXdEM9BPcLHxPH8TAeVD9al40HZlLBqYpkI7Yf/RRv8U4zz7uPRi4ohKcQAl5iCGvY5C7NuIUULf1UfSFeb4irzR7XTZo078MgBeALHM7V4+70ep7f1xCbTeXFpRR2XSD2jZCg5vfQ1fgfSnDhD9KESXdWSyYwqhSuXgRQBtFcYMSWRhWYloHgzbCh4M6hzWZtxtPAOcLmwXKeEjeX5+NIQNeyz0jqRnrB/bFDhlDrJXQl7FEzZScIhgEoczQ3sHBpNQptA5seODGzXyeOZLEBZsHyWQxYSCamMadRy2csEUkYYS5FemRyxBOgI7NoFB5ri/xlx8ZYeGFBNlhQAnA0D7HadV1QgWxuXcQut71cfgKyfE/SRSGj2JWiYq4TcwKbRpXBOsxn41nAYPis0LXChpgcduow6C08no62HeQYV5UCyxvnI3r60QDwFUVPZzdd3wiOoBQOh6Jmn9D
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
