apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBxFThcsOQmlNvPX2jkiBGDOsL0gzg+eS05cdV5COiDHOBVOr4e7CUxR8SAzaQTZkz5q3C/2rgkfgQ9CGIAdKjzpr/iK8SEtuaY/t5Oxl65JkSZOINjNjieZ1o+oj60538ld1p6VF6sMWF0UAQ3cpki3iUMjD6fpVA3C7RAGTGeRBADJNEvPDhOMIwTgbwS09773yEhXn6JDPCPvDYpnhusStKnZHDI1Ev9qxJtInmhT+21tOkkAjHEWGECer2F0zvcvptbrGvOQDsnbFWhwVV6RUNQ1EJE0tepKx9PA14la9fV8WA4sGqNjArAxZolrrPYtx9+Aszie28K7dWvdrws+J1yYVLn2rjkIAcu/KM4/uFafMO8sXb8qpoMwE2Aca0ETQOAHHLCFunvmeHOPc2SgNTE7GjXbFFqQQFPetWLvWhOkOg40HPwVuKglzwol+2PIsQPflESjsxB2nP7tEPBTPDst8SAtLWEbJqCpNp+hvTjLxomkpUfkVrGfM6sYiAObd6bzdUdtQVw0oDn3oKdHHSIlcr9fdXdtQgnMDquKK1/TLwfCzQViQgM+QCDnprMNS0bQ5W1wngJ990UahoaIx0KKosmkBWLb1lSA1hOputPOSpYZBK+Oz/gEFSbRATCEO18y/aD1+wdus451zfhCMN8EY7Lfgo5AiEGYpmyFojwG7zJTbn7caJ6a81bazgC+rASWGPxz1DzjhA=
    MINIO_SECRET_KEY: AgAJFVUYbojW7cae4SZ7i67S/k5Ybh7qOPyVFtC/0RdqHGHdjFTqrnwjJU7yVPvA4IinjGQBaxm5ulSZ12+JiYNXH4anHayuCy1rwSotIH3Dyh9QzVhzTB4NmAJmg3KP/VzYd9vM5KiFPUxHF1OpJ3+ngZcFZBvLcT5z23Gon3H15qpJ4Kxok39AktZvT6nBOeaGJrs2wlhYaUT1w/r3uPfOVwm5Crhm3pOaCZkD4QL37wb1NbkB/BK3JWt81k0I0bfUjSrZuvGrWbm9/Uryl0sH62o95oqi+BfL50B/uCcnyjIj4acmlCk13RORGOC/6pYqpYDZZz8hh8idxFU7Ym0dnS9Ea4rf0zbWw4nhaDw9Alxq0i9Ioc07JkQIYS5EYSL4S5eE09RYDrzLbyTLr4uRvhzAM+JVDf1KIIOyrExIZUZcGao8mVtWUhHNheAn0yx/9iEJUbntznLviItCkDdriZXIMCu3j2XnrImlW5rVUwBqo2PBHEyBFruA5n8vuijb4GuQYSY8LNxh7zPPwEAMu3brK41KyUpAQdS8noOhE4pSc8g5ywwx1bDEqOKVbIbNwZ0kmecovohYhUEwNaz0NKqwxoeM6zPv6zsly5D0Ib3XTQ+Ph9HqSr230doWrbC/b4uFBVS4mBgYe8UT0OpiWibtY07Dc4wL6JYJQqv1Zbpr3F074AzcOF3c40sojQTW0kR+qU/QbTGmZyvrraNmuAmNJwNjQYfKhVQzglFZCbrzRne3pu5nub9cGQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
