apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBxFThcsOQmlNvPX2jkiBGDOsL0gzg+eS05cdV5COiDHOBVOr4e7CUxR8SAzaQTZkz5q3C/2rgkfgQ9CGIAdKjzpr/iK8SEtuaY/t5Oxl65JkSZOINjNjieZ1o+oj60538ld1p6VF6sMWF0UAQ3cpki3iUMjD6fpVA3C7RAGTGeRBADJNEvPDhOMIwTgbwS09773yEhXn6JDPCPvDYpnhusStKnZHDI1Ev9qxJtInmhT+21tOkkAjHEWGECer2F0zvcvptbrGvOQDsnbFWhwVV6RUNQ1EJE0tepKx9PA14la9fV8WA4sGqNjArAxZolrrPYtx9+Aszie28K7dWvdrws+J1yYVLn2rjkIAcu/KM4/uFafMO8sXb8qpoMwE2Aca0ETQOAHHLCFunvmeHOPc2SgNTE7GjXbFFqQQFPetWLvWhOkOg40HPwVuKglzwol+2PIsQPflESjsxB2nP7tEPBTPDst8SAtLWEbJqCpNp+hvTjLxomkpUfkVrGfM6sYiAObd6bzdUdtQVw0oDn3oKdHHSIlcr9fdXdtQgnMDquKK1/TLwfCzQViQgM+QCDnprMNS0bQ5W1wngJ990UahoaIx0KKosmkBWLb1lSA1hOputPOSpYZBK+Oz/gEFSbRATCEO18y/aD1+wdus451zfhCMN8EY7Lfgo5AiEGYpmyFojwG7zJTbn7caJ6a81bazgC+rASWGPxz1DzjhA=
    MINIO_SECRET_KEY: AgBWyGzm+nLcZhVRl9y62PdUePXv4NgyiAxvrUgjeO/CixEJvv0osGaXT47Qrtl4dAYQ9xQf1IvRn1MbjYvTNJOehe6W5ybIXmQNQxK4CryOB6yP+v8qTaS7bmwRPjvsBtsnliU+rdc8oCAOjkUG7Dpp4HipbC7rtanXgdrPyyQkg+UKak1LxkEUGgkJRNNmCSnHCpNWyvINmuGAE9NQECSIDeXZQMgaekEl/CRAA+JkQTAc3alI0VrP1D8sEt6ivxjGoAuD/iO7E1xyJ5yq9IhnXa1EGnd7g7nERoX6Qv2MXk3aFje1XhlBOxHtjrLmNk38y3ExZIiEFdMuo/xNhQf+r30K999EBh1G2OnGg/AHeAAMedJKW2nDbV+aC1jE87rmzLb8f0YXDhBj05kiV3X7YEUphMasyiclhP5h5C4jyuXPxEq94UHWmZHJPCNkU9nTgZo3txb9dMWmuhE1/Jv4XH+L558ZbH79OejL32pJWjje0JAVhzck+yV+ZvnWrzT5qdFKk+pGdRpO5Kyox81HqtQA2iQQBITs8/jpjMEbXMwZniEtDQAwWFDGatmQRfxh5eRPaHP436QEjQfr4XMpke0s9iligo+PjHFKnjfNGJKLula59BE7xSIGcWrZTJI4LtNWaAdyLmVQN9c/Hk0aGowVKrrTtXxslfWQC8HY7wxEDXfUYZFQUYkc5RyctdLedAsRWppx68TF5BrtF5kt291LdJfoIco4/rR5nYIvmhvFSVQZ2YObrCbeZ+DYNquEOrzOSlbJzv3VDirmZKrD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
