apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: bratislava-next-msal-secret
  namespace: standalone
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgAWGVB+71padAZxwZvsv13KZZR+1D9OZkREuwXZQfxGvsWgnTZkgKpMTq7P/WDuUsd888Hm0sWu6FxugIUqMofrsGU7p4OeAZOkYiXrUDJ7i/djmp2NzDOIAkzGYWiqFoNkzrCWY8Maj58ZxHibj5ws/05gbCsAKSIKFSF7Gir0PWJ1oONjKu/j2zTcnHxT+Ko5vBwsYl6BhKdKeFWiCXiNHtcBP3YvfbExr6Omc5IJ5f+R/pxBB7aFAJZNmnpX2OOTuO52BJ3RrVTjFvqOWjsg2A3guGHSl/plm0hTQbVP8HutGHims68l2cMg27Nj6jaNh0JHROL6TQlpIrLqEwOHr0PQuDJDpgqpqV8/IBf954O4rVHjt9NCB3D0yNwfmhZB7N8E4lCSPDEouGgFw/5bvoFF0GAoLyFv1Gczjk0pWfmYn5rWmoKfASvp5+ENhpoGa3rqGTYiv7jtPgXa0p+jw4VKP2ILBG6T9ZpDl9TeMirjnT/4utUoTbADD5aa9X9LmS/nt/e1/dV5ice9n32en5uNLZIY6O7hk0ju5hr4VnNz4idZK5/4mbgarcDiu+I3SgPYDK3e8HSkSMI9nz+MiuT4Rt+vA6UNCTht0bYyUZaOw6VNdLAG0R6KqgEQou88/OTF4BvCRV5ubLKrkfxVMpdak+67qULVA/lwPJ0dn/Uu46aVtcdZfyOH07if8n5j7Be4JrlU0I3h04cKFEk7SZhfoaIXXyB06xQQHGsuGzrFx+HEAFV8
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: bratislava-next-msal-secret
      namespace: standalone
