apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: bratislava-next-msal-secret
  namespace: standalone
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgAvUwoQTfjtiJzw4xA+Dq3GZP6S3coN62ZjACZczX6eiyRj7GUVTKPfi0S2h1BCh96HJn/Q0wi/87tcl8Wmp0C9hj8Hf+9T+e1dxhhaWVAWnL32q6wivSHUQUuB9EqxChTUrnxyVS881jcda1PjKRaulZQF+DjY+kUACKWyJLGohbHaKUnJgEzH0AG6AsMS6oTVLHHJ1BRHGiDB7kBfdJuwI8/mtwcm5IWNLmsKIQa++NjfPXmB8NqIYa2KEss+BMyNrgbKo8ZsewgNsb9xUxVYnrMcv2Ws7x1WobGaNJ/bg5+Fpo4f5fr2FWWEuzWE5752sPnXuQjFw6Y0vA6wJimxjSSSMlX18iWGxiUnd1ptBo1qEv+Vzk6DPQpB6TBZee6ZDZrvA3fBuRyCCqgRV5EpO9LpnYWvzOoj0CkZrF/EvV7qXaQIfLS1ooW3SxzfGJSynOVvSEgkXS1OZKHHlF3IHBTBuT9GVXXaGo5fRP46SEpDxxLRjSWPCPR+XV85Qw9jX8JKoPSFWiFVEYY5FTSYT6yxvV6LfFp/N/cT46LVouVBsNnd895TpICeriy5qCaRM8N5i4PW5lgGAWii7zbT9JNlG6xgQlTJXSdysmD8qk5VK956gnsQSg9TUziEvo2zbYdi2oCvb4KSTVV8yhD/aukNCBlK6DiGBp3+++hZvoFFr0OjBPkvT0QStHR3bZUymzLok8IlBQ6XlNgF0EdVQJOTf6RXJJ97ivIF/LXrSh5A/e9Wipb1
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: bratislava-next-msal-secret
      namespace: standalone

