apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: bratislava-next-msal-secret
  namespace: standalone
spec:
  encryptedData:
    MSAL_CLIENT_SECRET: AgAICzAbuAYc7XyaYFx8mscSxqkwQjMUBfzXauPnAjY1y7lIbSvizaDdixP/fTCTkeHKnOfNEP2lkcjDrp2kih3LvltkW83GaL5StMkbFDaINETymgBw4iUU/Xo765+HgLOgc5LrE4jDjs5iclDGI0KjQ53wLDT3kdaV4N4L6I+5dRzSZtkKOXlB8bBFsowgNYfjCVLF689mWSJwcEvOefLW460eI3UwFipbGHzHREDEBzRGo0rJ+SsY1N64vHnuXX/iJTGcNvNXzx80D412lblQh0O+2Lj/54nwkACf4CB8/omQHx+YlpsKZk1IRcM6pPXldLFjn9FFCsV9oFdjFeIi4CZrALzzH8IwizifYBb5oADS+na5XnClB3hgBN3j03JYdBsxmT2B9+adIJ5+RKxmGEc29XkFy0Nfjz22JYunJKu36JV/VZWunQsc97mnjzjGE0SZxqK9pWzD3L4BCXNpZBjmRU3vZgCysqzIFaVjI+cjJJJg+5d9ip2GJ/gEL8qP0KDL83mpOqCyPjnNYLr2Zt9s98iljkUbTjHv7NJ74wNqJ3m6qTBZmG+lBTTk1BMGXd/Jo9rADWEf4+87oa8j1cnncFPQ/b8n9GGQOVv01hWsX4dxo3NDpSnh9La8uYC58lcSMPReZSdE4W3vifv/nj7rGBm7P3UiJklw56E387bB+Dx3ZtTPHB8s1+Ni2ftQ6jqiKyowdk0Bn/Xpv5zlMnvxMMN6XKXb1/cydbn+2i4ZqyXdtFml
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: bratislava-next-msal-secret
      namespace: standalone
