resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  - redirects/ukrajina.ingress.yml
  - redirects/platbadane.ingress.yml
  - redirects/izba.ingress.yml
  - redirects/nocnapomoc.ingress.yml
  - redirects/old_aliases.ingress.yml
  - redirects/klima.ingress.yml
  - redirects/camping.ingress.yml
  - redirects/horskypark.ingress.yml
  - redirects/kariera.ingress.yml
  - redirects/klimatickavyzva.ingress.yml
  - redirects/primacialnypalac.ingress.yml
configurations:
  - configuration.yml

# Keep as is
#namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}
  commit: ${COMMIT}
  tag: ${TAG}
  image: ${IMAGE}

configMapGenerator:
  - name: ${BUILD_REPOSITORY_NAME}-env
    namespace: ${NAMESPACE}
    envs:
      - .env
