apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgCaoASScVr9am1X4w/e4rRyXjvclF/KJS9EjWZJDwg8+QtQRa5HfNXe6ziM2sXt0LaL2EKtrP5+Gd3SNwu86q9KQ8oo91AxYQ+ZvdduJ5Bw5O05Ek7O+7sLWI8ga9W0DjQtSVDL/0Hy3Drba4w0lvdMtrvlDfHno5f7Manwymx/LAIQPqdQCWS8K0q3l0dXcpSGEJZAZCaKKg/7Pam6kQrdANCsWe6F46uooSaKSKH2VbPL2oPI0Q1F0jvDwrdbSQ2w6sw6THj1RF+3gSVEyxZJYBeUPhBzb/aY3oQWHy/moZ9rsmXUR6/GCD/nODEtCwnGvqssnpVFx3/UKesiGIbtKLirZRHQd4Eu80cT5flDNQTOf1TkbDNgM18PM0JTw/mLb7y9VaSQ/1kQShNUtLDzgA5Gm+rA4rmLIih40yGiK6IboAJtbYgBMgmmjXdYCEteBUhx0BQkgLkPJNA4QvjnpsxVpNI8OjSdvCdnKCfPcUqsZtAEVENP4NL5ycKpVMl9wkn4lbfZqlsl9aNoBPdFqb9c8ge+HYqJdsERqP/C1WbWsVM+teiCvIeqBiaD0M+8pbocYjf2IMIUrjmcPZrwCj9Q2mHsbFUEfNhBJ2ObtRNoOuLt/VOL0uOAVuzUmlPZ8V2OUq6X+xWEkb92u7PtVrvmv4siSz4Cvt6mjis4mcBHrf/8ka/wyjclYYLsDUIWPEe0+uK/Fxhck5WKJZ5EH0YMdhHSVzETIqQV9kHbVQnb5+6inJDBEQ45c6zR7iTeJA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
