name: Cypress test

on:
  workflow_run:
    workflows: ['Strapi/Next deploy pipeline']
    types:
      - completed

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20.x'

      - name: Run Cypress tests
        uses: cypress-io/github-action@248bde77443c376edc45906ede03a1aba9da0462 # v5.8.4
        with:
          working-directory: tests
          command: npm run cypress:run

      - name: Screenshots of errors during E2E tests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
          retention-days: 1
