name: Cypress test

on: [pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          command: npm run cypress:ci
      
      - name: Screenshots of errors during E2E tests
        uses: actions/upload-artifact@v3
        if: always() 
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
          retention-days: 1

      - name: Notify on Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_TITLE: 'Cypress tests failed'
          SLACK_MESSAGE: '@here Cypress tests after deployment to production failed. Investigate and fix the issues.'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
