name: Cypress test

on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          command: npm run cypress:ci
      
      - name: Screenshots of errors during E2E tests
        uses: actions/upload-artifact@v3
        if: always() 
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
          retention-days: 1

      - name: Notify on Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: |
            ${{ if eq(job.status, 'success') }} 
              Cypress tests after deployment to production passed successfully!
            ${{ else }}
              Cypress tests after deployment to production failed. Investigate and fix the issues.
            ${{ endif }}
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
